cmake_minimum_required(VERSION 3.13)

include(toolchain.cmake)

project(bsp)

enable_language(ASM)
enable_language(C)
enable_language(CXX)

set(BspLibraryName "freertos_bsp" CACHE STRING "The BSP library name.")
set(BspLinkerScript "${CMAKE_CURRENT_SOURCE_DIR}/linker.x" CACHE STRING
    "The linker script an app should use.")

# HAL library
add_library("${BspLibraryName}" STATIC "")

target_include_directories("${BspLibraryName}" PUBLIC
    .
    FREERTOS/inc
    FreeRTOS-Kernel/include
    FreeRTOS-Kernel/portable/GCC/RISC-V
    FreeRTOS-Kernel/portable/GCC/RISC-V/chip_specific_extensions/Intel_NiosV_RV32I_no_extensions
    FreeRTOS-Kernel/portable/MemMang
    FreeRTOS_TCP_IP/source
    FreeRTOS_TCP_IP/source/include
    FreeRTOS_TCP_IP/source/portable/Compiler/GCC
    FreeRTOS_TCP_IP/source/portable/NetworkInterface/AlteraTSE
    FreeRTOS_TCP_IP/source/portable/NetworkInterface/include
    HAL/inc
    drivers/inc
)

target_sources("${BspLibraryName}"
    PRIVATE
        HAL/src/alt_ecc_exception_entry.S
        HAL/src/alt_log_macro.S
        HAL/src/alt_mcount.S
        HAL/src/alt_vic_vector_table.S
        HAL/src/crt0.S
        HAL/src/machine_trap.S
        FREERTOS/src/alt_env_lock.c
        FREERTOS/src/alt_malloc_lock.c
        FREERTOS/src/heap_wrapper.c
        FreeRTOS-Kernel/croutine.c
        FreeRTOS-Kernel/event_groups.c
        FreeRTOS-Kernel/list.c
        FreeRTOS-Kernel/portable/GCC/RISC-V/port.c
        FreeRTOS-Kernel/portable/GCC/RISC-V/portASM.S
        FreeRTOS-Kernel/queue.c
        FreeRTOS-Kernel/stream_buffer.c
        FreeRTOS-Kernel/tasks.c
        FreeRTOS-Kernel/timers.c
        FreeRTOS_TCP_IP/source/FreeRTOS_ARP.c
        FreeRTOS_TCP_IP/source/FreeRTOS_BitConfig.c
        FreeRTOS_TCP_IP/source/FreeRTOS_DHCP.c
        FreeRTOS_TCP_IP/source/FreeRTOS_DHCPv6.c
        FreeRTOS_TCP_IP/source/FreeRTOS_DNS.c
        FreeRTOS_TCP_IP/source/FreeRTOS_DNS_Cache.c
        FreeRTOS_TCP_IP/source/FreeRTOS_DNS_Callback.c
        FreeRTOS_TCP_IP/source/FreeRTOS_DNS_Networking.c
        FreeRTOS_TCP_IP/source/FreeRTOS_DNS_Parser.c
        FreeRTOS_TCP_IP/source/FreeRTOS_ICMP.c
        FreeRTOS_TCP_IP/source/FreeRTOS_IP.c
        FreeRTOS_TCP_IP/source/FreeRTOS_IP_Timers.c
        FreeRTOS_TCP_IP/source/FreeRTOS_IP_Utils.c
        FreeRTOS_TCP_IP/source/FreeRTOS_IPv4.c
        FreeRTOS_TCP_IP/source/FreeRTOS_IPv4_Sockets.c
        FreeRTOS_TCP_IP/source/FreeRTOS_IPv4_Utils.c
        FreeRTOS_TCP_IP/source/FreeRTOS_IPv6.c
        FreeRTOS_TCP_IP/source/FreeRTOS_IPv6_Sockets.c
        FreeRTOS_TCP_IP/source/FreeRTOS_IPv6_Utils.c
        FreeRTOS_TCP_IP/source/FreeRTOS_ND.c
        FreeRTOS_TCP_IP/source/FreeRTOS_RA.c
        FreeRTOS_TCP_IP/source/FreeRTOS_Routing.c
        FreeRTOS_TCP_IP/source/FreeRTOS_Sockets.c
        FreeRTOS_TCP_IP/source/FreeRTOS_Stream_Buffer.c
        FreeRTOS_TCP_IP/source/FreeRTOS_TCP_IP.c
        FreeRTOS_TCP_IP/source/FreeRTOS_TCP_IP_IPv4.c
        FreeRTOS_TCP_IP/source/FreeRTOS_TCP_IP_IPv6.c
        FreeRTOS_TCP_IP/source/FreeRTOS_TCP_Reception.c
        FreeRTOS_TCP_IP/source/FreeRTOS_TCP_State_Handling.c
        FreeRTOS_TCP_IP/source/FreeRTOS_TCP_State_Handling_IPv4.c
        FreeRTOS_TCP_IP/source/FreeRTOS_TCP_State_Handling_IPv6.c
        FreeRTOS_TCP_IP/source/FreeRTOS_TCP_Transmission.c
        FreeRTOS_TCP_IP/source/FreeRTOS_TCP_Transmission_IPv4.c
        FreeRTOS_TCP_IP/source/FreeRTOS_TCP_Transmission_IPv6.c
        FreeRTOS_TCP_IP/source/FreeRTOS_TCP_Utils.c
        FreeRTOS_TCP_IP/source/FreeRTOS_TCP_Utils_IPv4.c
        FreeRTOS_TCP_IP/source/FreeRTOS_TCP_Utils_IPv6.c
        FreeRTOS_TCP_IP/source/FreeRTOS_TCP_WIN.c
        FreeRTOS_TCP_IP/source/FreeRTOS_Tiny_TCP.c
        FreeRTOS_TCP_IP/source/FreeRTOS_UDP_IP.c
        FreeRTOS_TCP_IP/source/FreeRTOS_UDP_IPv4.c
        FreeRTOS_TCP_IP/source/FreeRTOS_UDP_IPv6.c
        FreeRTOS_TCP_IP/source/portable/BufferManagement/BufferAllocation_1.c
        FreeRTOS_TCP_IP/source/portable/NetworkInterface/AlteraTSE/NetworkInterface.c
        FreeRTOS_TCP_IP/source/portable/NetworkInterface/AlteraTSE/msgdma_driver.c
        FreeRTOS_TCP_IP/source/portable/NetworkInterface/AlteraTSE/tse_driver.c
        FreeRTOS_TCP_IP/source/portable/NetworkInterface/Common/phyHandling.c
        HAL/src/alt_alarm_start.c
        HAL/src/alt_busy_sleep.c
        HAL/src/alt_close.c
        HAL/src/alt_dcache_flush.c
        HAL/src/alt_dcache_flush_all.c
        HAL/src/alt_dcache_flush_no_writeback.c
        HAL/src/alt_dev.c
        HAL/src/alt_dev_llist_insert.c
        HAL/src/alt_dma_rxchan_open.c
        HAL/src/alt_dma_txchan_open.c
        HAL/src/alt_do_ctors.c
        HAL/src/alt_do_dtors.c
        HAL/src/alt_ecc_error_inject.c
        HAL/src/alt_ecc_exception.c
        HAL/src/alt_environ.c
        HAL/src/alt_errno.c
        HAL/src/alt_execve.c
        HAL/src/alt_exit.c
        HAL/src/alt_fcntl.c
        HAL/src/alt_fd_lock.c
        HAL/src/alt_fd_unlock.c
        HAL/src/alt_find_dev.c
        HAL/src/alt_find_file.c
        HAL/src/alt_flash_dev.c
        HAL/src/alt_fork.c
        HAL/src/alt_fs_reg.c
        HAL/src/alt_fstat.c
        HAL/src/alt_get_fd.c
        HAL/src/alt_getchar.c
        HAL/src/alt_getpid.c
        HAL/src/alt_gettod.c
        HAL/src/alt_gmon.c
        HAL/src/alt_icache_flush.c
        HAL/src/alt_icache_flush_all.c
        HAL/src/alt_iic.c
        HAL/src/alt_iic_isr_register.c
        HAL/src/alt_instruction_exception_register.c
        HAL/src/alt_io_redirect.c
        HAL/src/alt_ioctl.c
        HAL/src/alt_irq_handler.c
        HAL/src/alt_isatty.c
        HAL/src/alt_kill.c
        HAL/src/alt_link.c
        HAL/src/alt_load.c
        HAL/src/alt_log_printf.c
        HAL/src/alt_lseek.c
        HAL/src/alt_main.c
        HAL/src/alt_open.c
        HAL/src/alt_printf.c
        HAL/src/alt_putchar.c
        HAL/src/alt_putcharbuf.c
        HAL/src/alt_putstr.c
        HAL/src/alt_read.c
        HAL/src/alt_release_fd.c
        HAL/src/alt_remap_cached.c
        HAL/src/alt_remap_uncached.c
        HAL/src/alt_rename.c
        HAL/src/alt_sbrk.c
        HAL/src/alt_settod.c
        HAL/src/alt_stat.c
        HAL/src/alt_tick.c
        HAL/src/alt_times.c
        HAL/src/alt_tls.c
        HAL/src/alt_uncached_free.c
        HAL/src/alt_uncached_malloc.c
        HAL/src/alt_unlink.c
        HAL/src/alt_usleep.c
        HAL/src/alt_vic_isr_wrapper.c
        HAL/src/alt_wait.c
        HAL/src/alt_write.c
        HAL/src/intel_fpga_api_cmn_dfl.c
        HAL/src/intel_fpga_api_cmn_inf.c
        HAL/src/intel_fpga_api_cmn_msg.c
        HAL/src/intel_fpga_api_niosv.c
        HAL/src/intel_fpga_platform_api_niosv.c
        HAL/src/intel_niosv_irq.c
        HAL/src/mtimer.c
        HAL/src/os_cpu_c.c
        alt_sys_init.c
        drivers/src/altera_avalon_jtag_uart_fd.c
        drivers/src/altera_avalon_jtag_uart_init.c
        drivers/src/altera_avalon_jtag_uart_ioctl.c
        drivers/src/altera_avalon_jtag_uart_read.c
        drivers/src/altera_avalon_jtag_uart_write.c
        drivers/src/altera_avalon_sysid_qsys.c
        drivers/src/altera_msgdma.c
        drivers/src/intel_avalon_tse.c
        drivers/src/intel_avalon_tse_system_info.c
    PUBLIC
        FREERTOS/inc/FreeRTOSConfig.h
        FREERTOS/inc/os/alt_flag.h
        FREERTOS/inc/os/alt_hooks.h
        FREERTOS/inc/os/alt_sem.h
        FREERTOS/inc/priv/alt_flag_freertos.h
        FREERTOS/inc/priv/alt_sem_freertos.h
        FreeRTOS-Kernel/include/FreeRTOS.h
        FreeRTOS-Kernel/include/atomic.h
        FreeRTOS-Kernel/include/croutine.h
        FreeRTOS-Kernel/include/deprecated_definitions.h
        FreeRTOS-Kernel/include/event_groups.h
        FreeRTOS-Kernel/include/list.h
        FreeRTOS-Kernel/include/message_buffer.h
        FreeRTOS-Kernel/include/mpu_prototypes.h
        FreeRTOS-Kernel/include/mpu_wrappers.h
        FreeRTOS-Kernel/include/portable.h
        FreeRTOS-Kernel/include/projdefs.h
        FreeRTOS-Kernel/include/queue.h
        FreeRTOS-Kernel/include/semphr.h
        FreeRTOS-Kernel/include/stack_macros.h
        FreeRTOS-Kernel/include/stream_buffer.h
        FreeRTOS-Kernel/include/task.h
        FreeRTOS-Kernel/include/timers.h
        FreeRTOS-Kernel/portable/GCC/RISC-V/chip_specific_extensions/Intel_NiosV_RV32I_no_extensions/freertos_risc_v_chip_specific_extensions.h
        FreeRTOS-Kernel/portable/GCC/RISC-V/portContext.h
        FreeRTOS-Kernel/portable/GCC/RISC-V/portmacro.h
        FreeRTOS_TCP_IP/source/include/FreeRTOSIPConfig.h
        FreeRTOS_TCP_IP/source/include/FreeRTOSIPConfigDefaults.h
        FreeRTOS_TCP_IP/source/include/FreeRTOSIPDeprecatedDefinitions.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_ARP.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_BitConfig.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_DHCP.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_DHCPv6.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_DNS.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_DNS_Cache.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_DNS_Callback.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_DNS_Globals.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_DNS_Networking.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_DNS_Parser.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_ICMP.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_IP.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_IP_Common.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_IP_Private.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_IP_Timers.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_IP_Utils.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_IPv4.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_IPv4_Private.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_IPv4_Sockets.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_IPv4_Utils.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_IPv6.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_IPv6_Private.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_IPv6_Sockets.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_IPv6_Utils.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_ND.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_Routing.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_Sockets.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_Stream_Buffer.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_TCP_IP.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_TCP_Reception.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_TCP_State_Handling.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_TCP_Transmission.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_TCP_Utils.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_TCP_WIN.h
        FreeRTOS_TCP_IP/source/include/FreeRTOS_UDP_IP.h
        FreeRTOS_TCP_IP/source/include/IPTraceMacroDefaults.h
        FreeRTOS_TCP_IP/source/include/NetworkBufferManagement.h
        FreeRTOS_TCP_IP/source/include/NetworkInterface.h
        FreeRTOS_TCP_IP/source/portable/Compiler/GCC/pack_struct_end.h
        FreeRTOS_TCP_IP/source/portable/Compiler/GCC/pack_struct_start.h
        FreeRTOS_TCP_IP/source/portable/NetworkInterface/AlteraTSE/msgdma_driver.h
        FreeRTOS_TCP_IP/source/portable/NetworkInterface/AlteraTSE/tse_driver.h
        FreeRTOS_TCP_IP/source/portable/NetworkInterface/include/phyHandling.h
        HAL/inc/alt_niosv_int_mode.h
        HAL/inc/alt_types.h
        HAL/inc/intel_fpga_api.h
        HAL/inc/intel_fpga_platform.h
        HAL/inc/intel_fpga_platform_api.h
        HAL/inc/intel_niosv.h
        HAL/inc/intel_niosv_g.h
        HAL/inc/intel_niosv_g_irq.h
        HAL/inc/intel_niosv_irq.h
        HAL/inc/io.h
        HAL/inc/os/alt_syscall.h
        HAL/inc/os_cpu.h
        HAL/inc/priv/alt_alarm.h
        HAL/inc/priv/alt_busy_sleep.h
        HAL/inc/priv/alt_dev_llist.h
        HAL/inc/priv/alt_exception_handler_registry.h
        HAL/inc/priv/alt_file.h
        HAL/inc/priv/alt_iic_isr_register.h
        HAL/inc/priv/alt_irq_table.h
        HAL/inc/priv/alt_no_error.h
        HAL/inc/priv/intel_niosv_gmon_data.h
        HAL/inc/sys/alt_alarm.h
        HAL/inc/sys/alt_cache.h
        HAL/inc/sys/alt_debug.h
        HAL/inc/sys/alt_dev.h
        HAL/inc/sys/alt_dma.h
        HAL/inc/sys/alt_dma_dev.h
        HAL/inc/sys/alt_driver.h
        HAL/inc/sys/alt_ecc_error_inject.h
        HAL/inc/sys/alt_ecc_exception.h
        HAL/inc/sys/alt_errno.h
        HAL/inc/sys/alt_exceptions.h
        HAL/inc/sys/alt_flash.h
        HAL/inc/sys/alt_flash_dev.h
        HAL/inc/sys/alt_flash_types.h
        HAL/inc/sys/alt_irq.h
        HAL/inc/sys/alt_llist.h
        HAL/inc/sys/alt_load.h
        HAL/inc/sys/alt_log_printf.h
        HAL/inc/sys/alt_set_args.h
        HAL/inc/sys/alt_sim.h
        HAL/inc/sys/alt_stack.h
        HAL/inc/sys/alt_stdio.h
        HAL/inc/sys/alt_sys_init.h
        HAL/inc/sys/alt_sys_wrappers.h
        HAL/inc/sys/alt_timestamp.h
        HAL/inc/sys/alt_tls.h
        HAL/inc/sys/alt_warning.h
        HAL/inc/sys/intel_fpga_api_cmn_dfl.h
        HAL/inc/sys/intel_fpga_api_cmn_inf.h
        HAL/inc/sys/intel_fpga_api_cmn_msg.h
        HAL/inc/sys/intel_fpga_api_niosv.h
        HAL/inc/sys/intel_fpga_platform_api_niosv.h
        HAL/inc/sys/intel_fpga_platform_niosv.h
        HAL/inc/sys/ioctl.h
        HAL/inc/sys/msw_interrupt.h
        HAL/inc/sys/termios.h
        drivers/inc/altera_avalon_jtag_uart.h
        drivers/inc/altera_avalon_jtag_uart_fd.h
        drivers/inc/altera_avalon_jtag_uart_regs.h
        drivers/inc/altera_avalon_pio_regs.h
        drivers/inc/altera_avalon_sysid_qsys.h
        drivers/inc/altera_avalon_sysid_qsys_regs.h
        drivers/inc/altera_msgdma.h
        drivers/inc/altera_msgdma_csr_regs.h
        drivers/inc/altera_msgdma_descriptor_regs.h
        drivers/inc/altera_msgdma_prefetcher_regs.h
        drivers/inc/altera_msgdma_response_regs.h
        drivers/inc/intel_avalon_tse.h
        drivers/inc/intel_avalon_tse_system_info.h
        drivers/inc/intel_eth_tse.h
        drivers/inc/intel_eth_tse_regs.h
        system.h
)

set(ExtraArchiveLibraries CACHE INTERNAL "")
