/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'intel_niosv_g_0' in SOPC Builder design 'qsys_top'
 *
 * Generated: Wed Oct 22 05:35:58 PDT 2025
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "intel_niosv_g"
#define ALT_CPU_CLIC_EN 0
#define ALT_CPU_CPU_FREQ 100000000u
#define ALT_CPU_DATA_ADDR_WIDTH 0x20
#define ALT_CPU_DCACHE_LINE_SIZE 32
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_DCACHE_SIZE 4096
#define ALT_CPU_FREQ 100000000
#define ALT_CPU_HAS_CSR_SUPPORT 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_ICACHE_LINE_SIZE 32
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_ICACHE_SIZE 4096
#define ALT_CPU_INST_ADDR_WIDTH 0x20
#define ALT_CPU_INT_MODE 0
#define ALT_CPU_MTIME_OFFSET 0x00212400
#define ALT_CPU_NAME "intel_niosv_g_0"
#define ALT_CPU_NIOSV_CORE_VARIANT 3
#define ALT_CPU_NUM_GPR 32
#define ALT_CPU_NUM_SRF_BANKS 1
#define ALT_CPU_RESET_ADDR 0x00000000
#define ALT_CPU_TICKS_PER_SEC NIOSV_INTERNAL_TIMER_TICKS_PER_SECOND
#define ALT_CPU_TIMER_DEVICE_TYPE 2


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define BANTAMLAKE_CLIC_EN 0
#define BANTAMLAKE_CPU_FREQ 100000000u
#define BANTAMLAKE_DATA_ADDR_WIDTH 0x20
#define BANTAMLAKE_DCACHE_LINE_SIZE 32
#define BANTAMLAKE_DCACHE_LINE_SIZE_LOG2 5
#define BANTAMLAKE_DCACHE_SIZE 4096
#define BANTAMLAKE_HAS_CSR_SUPPORT 1
#define BANTAMLAKE_HAS_DEBUG_STUB
#define BANTAMLAKE_ICACHE_LINE_SIZE 32
#define BANTAMLAKE_ICACHE_LINE_SIZE_LOG2 5
#define BANTAMLAKE_ICACHE_SIZE 4096
#define BANTAMLAKE_INST_ADDR_WIDTH 0x20
#define BANTAMLAKE_INT_MODE 0
#define BANTAMLAKE_MTIME_OFFSET 0x00212400
#define BANTAMLAKE_NIOSV_CORE_VARIANT 3
#define BANTAMLAKE_NUM_GPR 32
#define BANTAMLAKE_NUM_SRF_BANKS 1
#define BANTAMLAKE_RESET_ADDR 0x00000000
#define BANTAMLAKE_TICKS_PER_SEC NIOSV_INTERNAL_TIMER_TICKS_PER_SECOND
#define BANTAMLAKE_TIMER_DEVICE_TYPE 2


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_PIO
#define __ALTERA_AVALON_SYSID_QSYS
#define __ALTERA_MSGDMA
#define __INTEL_ETH_TSE
#define __INTEL_NIOSV_G
#define __INTEL_ONCHIP_MEMORY


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "AGILEX5"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/sys_jtag_uart"
#define ALT_STDERR_BASE 0x2124d8
#define ALT_STDERR_DEV sys_jtag_uart
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/sys_jtag_uart"
#define ALT_STDIN_BASE 0x2124d8
#define ALT_STDIN_DEV sys_jtag_uart
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/sys_jtag_uart"
#define ALT_STDOUT_BASE 0x2124d8
#define ALT_STDOUT_DEV sys_jtag_uart
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSID_BASE SYS_SYSID_BASE
#define ALT_SYSID_ID SYS_SYSID_ID
#define ALT_SYSTEM_NAME "qsys_top"
#define ALT_SYS_CLK_TICKS_PER_SEC ALT_CPU_TICKS_PER_SEC
#define ALT_TIMESTAMP_CLK_TIMER_DEVICE_TYPE ALT_CPU_TIMER_DEVICE_TYPE


/*
 * freertos configuration
 *
 */

#define HEAP_METHOD 4
#define OS_APPLICATION_ALLOCATED_HEAP 0
#define OS_CHECK_STACK_OVERFLOW 1
#define OS_COUNTING_SEM_EN 1
#define OS_ENABLE_HEAP_PROTECTOR 1
#define OS_EVENT_GROUP_SET_BIT_FROM_ISR 1
#define OS_GENERATE_RUN_TIME_STATS 0
#define OS_HEAP_CLEAR_MEMORY_ON_FREE 1
#define OS_IDLE_SHOULD_YEILD 0
#define OS_MALLOC_FAILED_HOOK_EN 0
#define OS_MAX_CO_ROUTINE_PRIORITIES 1
#define OS_MAX_PRIORITIES 7
#define OS_MAX_TASK_NAME_LEN 16
#define OS_MEMORY_DYNAMIC_ALLOCATION_EN 1
#define OS_MEMORY_STATIC_ALLOCATION_EN 0
#define OS_MIN_STACK_SIZE 300
#define OS_MUTEX_EN 1
#define OS_NUM_THREAD_LOCAL_STORAGE_POINTERS 0
#define OS_PORT_HAS_MTIME 1
#define OS_PORT_OPTIMISED_TASK_SELECTION 0
#define OS_Q_REG_SIZE 8
#define OS_RECURSIVE_MUTEX_EN 1
#define OS_SEMAPHORE_GET_MUTEX_HOLDER_EN 1
#define OS_STACK_ALLOCATION_FROM_SEPARATE_HEAP 0
#define OS_STATS_BUFFER_MAX_LENGTH 4095
#define OS_TASK_ABORT_DELAY_EN 1
#define OS_TASK_CLEAN_UP_RESOURCES_EN 1
#define OS_TASK_DELAY_EN 1
#define OS_TASK_DELAY_UNTIL_EN 1
#define OS_TASK_DELETE_EN 1
#define OS_TASK_GET_CURRENT_TASK_HANDLE_EN 1
#define OS_TASK_GET_HANDLE_EN 1
#define OS_TASK_GET_IDLE_TASK_HANDLE_EN 1
#define OS_TASK_GET_SCHEDULER_STATE_EN 1
#define OS_TASK_GET_STACK_HIGH_WATERMARK2_EN 1
#define OS_TASK_GET_STACK_HIGH_WATERMARK_EN 1
#define OS_TASK_GET_STATE_EN 1
#define OS_TASK_NOTIFICATION_ARRAY_ENTRIES 1
#define OS_TASK_PRIORITY_GET_EN 1
#define OS_TASK_PRIORITY_SET_EN 1
#define OS_TASK_SUSPEND_EN 1
#define OS_THREAD_SAFE_C_LIBRARY 1
#define OS_TICKS_PER_SEC ALT_SYS_CLK_TICKS_PER_SEC
#define OS_TIMER_PEND_FUNCTION_CALL_EN 1
#define OS_TIMER_QUEUE_LEN 8
#define OS_TIMER_TASK_DEPTH 160
#define OS_TLS_BYTES_PER_TASK 256
#define OS_TOTAL_HEAP_SIZE 80000
#define OS_USE_16_BIT_TICKS 0
#define OS_USE_APPLICATION_TASK_TAG 0
#define OS_USE_CO_ROUTINES 1
#define OS_USE_DAEMON_TASK_STARTUP_HOOK 0
#define OS_USE_IDLE_HOOK 0
#define OS_USE_MINI_LIST_ITEM 1
#define OS_USE_NEWLIB_REENTRANT 0
#define OS_USE_POSIX_ERRNO 0
#define OS_USE_PREEMPTION 1
#define OS_USE_QUEUE_SETS 1
#define OS_USE_STATS_FORMATTING_FUNCTIONS 0
#define OS_USE_STREAM_BUFFER_COMPLETED_CALLBACK 0
#define OS_USE_TASK_NOTIFICATIONS 1
#define OS_USE_TICKLESS_IDLE 0
#define OS_USE_TICK_HOOK 1
#define OS_USE_TIMERS 1
#define OS_USE_TIME_SLICING 1
#define OS_USE_TRACE_FACILITY 1


/*
 * hal2 configuration
 *
 */

#define ALT_MAX_FD 32
#define ALT_SYS_CLK INTEL_NIOSV_G_0
#define ALT_TIMESTAMP_CLK INTEL_NIOSV_G_0
#define INTEL_FPGA_DFL_START_ADDRESS 0xffffffffffffffff
#define INTEL_FPGA_USE_DFL_WALKER 0


/*
 * intel_niosv_g_0_dm_agent configuration
 *
 */

#define ALT_MODULE_CLASS_intel_niosv_g_0_dm_agent intel_niosv_g
#define INTEL_NIOSV_G_0_DM_AGENT_BASE 0x200000
#define INTEL_NIOSV_G_0_DM_AGENT_CLIC_EN 0
#define INTEL_NIOSV_G_0_DM_AGENT_CPU_FREQ 100000000u
#define INTEL_NIOSV_G_0_DM_AGENT_DATA_ADDR_WIDTH 0x20
#define INTEL_NIOSV_G_0_DM_AGENT_DCACHE_LINE_SIZE 32
#define INTEL_NIOSV_G_0_DM_AGENT_DCACHE_LINE_SIZE_LOG2 5
#define INTEL_NIOSV_G_0_DM_AGENT_DCACHE_SIZE 4096
#define INTEL_NIOSV_G_0_DM_AGENT_HAS_CSR_SUPPORT 1
#define INTEL_NIOSV_G_0_DM_AGENT_HAS_DEBUG_STUB
#define INTEL_NIOSV_G_0_DM_AGENT_ICACHE_LINE_SIZE 32
#define INTEL_NIOSV_G_0_DM_AGENT_ICACHE_LINE_SIZE_LOG2 5
#define INTEL_NIOSV_G_0_DM_AGENT_ICACHE_SIZE 4096
#define INTEL_NIOSV_G_0_DM_AGENT_INST_ADDR_WIDTH 0x20
#define INTEL_NIOSV_G_0_DM_AGENT_INT_MODE 0
#define INTEL_NIOSV_G_0_DM_AGENT_IRQ -1
#define INTEL_NIOSV_G_0_DM_AGENT_IRQ_INTERRUPT_CONTROLLER_ID -1
#define INTEL_NIOSV_G_0_DM_AGENT_MTIME_OFFSET 0x00212400
#define INTEL_NIOSV_G_0_DM_AGENT_NAME "/dev/intel_niosv_g_0_dm_agent"
#define INTEL_NIOSV_G_0_DM_AGENT_NIOSV_CORE_VARIANT 3
#define INTEL_NIOSV_G_0_DM_AGENT_NUM_GPR 32
#define INTEL_NIOSV_G_0_DM_AGENT_NUM_SRF_BANKS 1
#define INTEL_NIOSV_G_0_DM_AGENT_RESET_ADDR 0x00000000
#define INTEL_NIOSV_G_0_DM_AGENT_SPAN 65536
#define INTEL_NIOSV_G_0_DM_AGENT_TICKS_PER_SEC NIOSV_INTERNAL_TIMER_TICKS_PER_SECOND
#define INTEL_NIOSV_G_0_DM_AGENT_TIMER_DEVICE_TYPE 2
#define INTEL_NIOSV_G_0_DM_AGENT_TYPE "intel_niosv_g"


/*
 * intel_niosv_g_0_timer_sw_agent configuration
 *
 */

#define ALT_MODULE_CLASS_intel_niosv_g_0_timer_sw_agent intel_niosv_g
#define INTEL_NIOSV_G_0_TIMER_SW_AGENT_BASE 0x212400
#define INTEL_NIOSV_G_0_TIMER_SW_AGENT_CLIC_EN 0
#define INTEL_NIOSV_G_0_TIMER_SW_AGENT_CPU_FREQ 100000000u
#define INTEL_NIOSV_G_0_TIMER_SW_AGENT_DATA_ADDR_WIDTH 0x20
#define INTEL_NIOSV_G_0_TIMER_SW_AGENT_DCACHE_LINE_SIZE 32
#define INTEL_NIOSV_G_0_TIMER_SW_AGENT_DCACHE_LINE_SIZE_LOG2 5
#define INTEL_NIOSV_G_0_TIMER_SW_AGENT_DCACHE_SIZE 4096
#define INTEL_NIOSV_G_0_TIMER_SW_AGENT_HAS_CSR_SUPPORT 1
#define INTEL_NIOSV_G_0_TIMER_SW_AGENT_HAS_DEBUG_STUB
#define INTEL_NIOSV_G_0_TIMER_SW_AGENT_ICACHE_LINE_SIZE 32
#define INTEL_NIOSV_G_0_TIMER_SW_AGENT_ICACHE_LINE_SIZE_LOG2 5
#define INTEL_NIOSV_G_0_TIMER_SW_AGENT_ICACHE_SIZE 4096
#define INTEL_NIOSV_G_0_TIMER_SW_AGENT_INST_ADDR_WIDTH 0x20
#define INTEL_NIOSV_G_0_TIMER_SW_AGENT_INT_MODE 0
#define INTEL_NIOSV_G_0_TIMER_SW_AGENT_IRQ -1
#define INTEL_NIOSV_G_0_TIMER_SW_AGENT_IRQ_INTERRUPT_CONTROLLER_ID -1
#define INTEL_NIOSV_G_0_TIMER_SW_AGENT_MTIME_OFFSET 0x00212400
#define INTEL_NIOSV_G_0_TIMER_SW_AGENT_NAME "/dev/intel_niosv_g_0_timer_sw_agent"
#define INTEL_NIOSV_G_0_TIMER_SW_AGENT_NIOSV_CORE_VARIANT 3
#define INTEL_NIOSV_G_0_TIMER_SW_AGENT_NUM_GPR 32
#define INTEL_NIOSV_G_0_TIMER_SW_AGENT_NUM_SRF_BANKS 1
#define INTEL_NIOSV_G_0_TIMER_SW_AGENT_RESET_ADDR 0x00000000
#define INTEL_NIOSV_G_0_TIMER_SW_AGENT_SPAN 64
#define INTEL_NIOSV_G_0_TIMER_SW_AGENT_TICKS_PER_SEC NIOSV_INTERNAL_TIMER_TICKS_PER_SECOND
#define INTEL_NIOSV_G_0_TIMER_SW_AGENT_TIMER_DEVICE_TYPE 2
#define INTEL_NIOSV_G_0_TIMER_SW_AGENT_TYPE "intel_niosv_g"


/*
 * intel_niosv_g_freertos_driver configuration
 *
 */

#define NIOSV_INTERNAL_TIMER_TICKS_PER_SECOND 1000


/*
 * sys_cpu_ram configuration
 *
 */

#define ALT_MODULE_CLASS_sys_cpu_ram intel_onchip_memory
#define SYS_CPU_RAM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define SYS_CPU_RAM_BASE 0x0
#define SYS_CPU_RAM_CONTENTS_INFO ""
#define SYS_CPU_RAM_DUAL_PORT 0
#define SYS_CPU_RAM_GUI_RAM_BLOCK_TYPE "AUTO"
#define SYS_CPU_RAM_INIT_CONTENTS_FILE "qsys_top_intel_onchip_memory_1_sys_cpu_ram"
#define SYS_CPU_RAM_INIT_MEM_CONTENT 1
#define SYS_CPU_RAM_INSTANCE_ID "NONE"
#define SYS_CPU_RAM_IRQ -1
#define SYS_CPU_RAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SYS_CPU_RAM_NAME "/dev/sys_cpu_ram"
#define SYS_CPU_RAM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define SYS_CPU_RAM_RAM_BLOCK_TYPE "AUTO"
#define SYS_CPU_RAM_READ_DURING_WRITE_MODE "DONT_CARE"
#define SYS_CPU_RAM_SINGLE_CLOCK_OP 0
#define SYS_CPU_RAM_SIZE_MULTIPLE 1
#define SYS_CPU_RAM_SIZE_VALUE 2000000
#define SYS_CPU_RAM_SPAN 2000000
#define SYS_CPU_RAM_TYPE "intel_onchip_memory"
#define SYS_CPU_RAM_WRITABLE 1


/*
 * sys_desc_mem configuration
 *
 */

#define ALT_MODULE_CLASS_sys_desc_mem intel_onchip_memory
#define SYS_DESC_MEM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define SYS_DESC_MEM_BASE 0x210000
#define SYS_DESC_MEM_CONTENTS_INFO ""
#define SYS_DESC_MEM_DUAL_PORT 0
#define SYS_DESC_MEM_GUI_RAM_BLOCK_TYPE "AUTO"
#define SYS_DESC_MEM_INIT_CONTENTS_FILE "qsys_top_intel_onchip_memory_0_sys_desc_mem"
#define SYS_DESC_MEM_INIT_MEM_CONTENT 1
#define SYS_DESC_MEM_INSTANCE_ID "NONE"
#define SYS_DESC_MEM_IRQ -1
#define SYS_DESC_MEM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SYS_DESC_MEM_NAME "/dev/sys_desc_mem"
#define SYS_DESC_MEM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define SYS_DESC_MEM_RAM_BLOCK_TYPE "AUTO"
#define SYS_DESC_MEM_READ_DURING_WRITE_MODE "DONT_CARE"
#define SYS_DESC_MEM_SINGLE_CLOCK_OP 0
#define SYS_DESC_MEM_SIZE_MULTIPLE 1
#define SYS_DESC_MEM_SIZE_VALUE 8192
#define SYS_DESC_MEM_SPAN 8192
#define SYS_DESC_MEM_TYPE "intel_onchip_memory"
#define SYS_DESC_MEM_WRITABLE 1


/*
 * sys_jtag_uart configuration
 *
 */

#define ALT_MODULE_CLASS_sys_jtag_uart altera_avalon_jtag_uart
#define SYS_JTAG_UART_BASE 0x2124d8
#define SYS_JTAG_UART_IRQ 0
#define SYS_JTAG_UART_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SYS_JTAG_UART_NAME "/dev/sys_jtag_uart"
#define SYS_JTAG_UART_READ_DEPTH 64
#define SYS_JTAG_UART_READ_THRESHOLD 8
#define SYS_JTAG_UART_SPAN 8
#define SYS_JTAG_UART_TYPE "altera_avalon_jtag_uart"
#define SYS_JTAG_UART_WRITE_DEPTH 64
#define SYS_JTAG_UART_WRITE_THRESHOLD 8


/*
 * sys_led_pio configuration
 *
 */

#define ALT_MODULE_CLASS_sys_led_pio altera_avalon_pio
#define SYS_LED_PIO_BASE 0x2124c0
#define SYS_LED_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define SYS_LED_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SYS_LED_PIO_CAPTURE 0
#define SYS_LED_PIO_DATA_WIDTH 4
#define SYS_LED_PIO_DO_TEST_BENCH_WIRING 0
#define SYS_LED_PIO_DRIVEN_SIM_VALUE 0
#define SYS_LED_PIO_EDGE_TYPE "NONE"
#define SYS_LED_PIO_FREQ 100000000
#define SYS_LED_PIO_HAS_IN 0
#define SYS_LED_PIO_HAS_OUT 1
#define SYS_LED_PIO_HAS_TRI 0
#define SYS_LED_PIO_IRQ -1
#define SYS_LED_PIO_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SYS_LED_PIO_IRQ_TYPE "NONE"
#define SYS_LED_PIO_NAME "/dev/sys_led_pio"
#define SYS_LED_PIO_RESET_VALUE 0
#define SYS_LED_PIO_SPAN 16
#define SYS_LED_PIO_TYPE "altera_avalon_pio"


/*
 * sys_sysid configuration
 *
 */

#define ALT_MODULE_CLASS_sys_sysid altera_avalon_sysid_qsys
#define SYS_SYSID_BASE 0x2124d0
#define SYS_SYSID_ID -87110914
#define SYS_SYSID_IRQ -1
#define SYS_SYSID_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SYS_SYSID_NAME "/dev/sys_sysid"
#define SYS_SYSID_SPAN 8
#define SYS_SYSID_TYPE "altera_avalon_sysid_qsys"


/*
 * sys_tse configuration
 *
 */

#define ALT_MODULE_CLASS_sys_tse intel_eth_tse
#define SYS_TSE_BASE 0x212000
#define SYS_TSE_ENABLE_MACLITE 0
#define SYS_TSE_FIFO_WIDTH 32
#define SYS_TSE_IRQ -1
#define SYS_TSE_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SYS_TSE_IS_MULTICHANNEL_MAC 0
#define SYS_TSE_MACLITE_GIGE 0
#define SYS_TSE_MDIO_SHARED 0
#define SYS_TSE_NAME "/dev/sys_tse"
#define SYS_TSE_NUMBER_OF_CHANNEL 4
#define SYS_TSE_NUMBER_OF_MAC_MDIO_SHARED 4
#define SYS_TSE_PCS 0
#define SYS_TSE_PCS_ID 16843009
#define SYS_TSE_PCS_SGMII 0
#define SYS_TSE_RECEIVE_FIFO_DEPTH 8192
#define SYS_TSE_REGISTER_SHARED 0
#define SYS_TSE_RGMII 1
#define SYS_TSE_SPAN 1024
#define SYS_TSE_TRANSMIT_FIFO_DEPTH 8192
#define SYS_TSE_TYPE "intel_eth_tse"
#define SYS_TSE_USE_MDIO 1


/*
 * sys_tse_msgdma_rx_csr configuration
 *
 */

#define ALT_MODULE_CLASS_sys_tse_msgdma_rx_csr altera_msgdma
#define SYS_TSE_MSGDMA_RX_CSR_BASE 0x2124a0
#define SYS_TSE_MSGDMA_RX_CSR_BURST_ENABLE 0
#define SYS_TSE_MSGDMA_RX_CSR_BURST_WRAPPING_SUPPORT 0
#define SYS_TSE_MSGDMA_RX_CSR_CHANNEL_ENABLE 0
#define SYS_TSE_MSGDMA_RX_CSR_CHANNEL_ENABLE_DERIVED 0
#define SYS_TSE_MSGDMA_RX_CSR_CHANNEL_WIDTH 8
#define SYS_TSE_MSGDMA_RX_CSR_DATA_FIFO_DEPTH 2048
#define SYS_TSE_MSGDMA_RX_CSR_DATA_WIDTH 32
#define SYS_TSE_MSGDMA_RX_CSR_DESCRIPTOR_FIFO_DEPTH 128
#define SYS_TSE_MSGDMA_RX_CSR_DMA_MODE 2
#define SYS_TSE_MSGDMA_RX_CSR_ENHANCED_FEATURES 0
#define SYS_TSE_MSGDMA_RX_CSR_ERROR_ENABLE 1
#define SYS_TSE_MSGDMA_RX_CSR_ERROR_ENABLE_DERIVED 1
#define SYS_TSE_MSGDMA_RX_CSR_ERROR_WIDTH 6
#define SYS_TSE_MSGDMA_RX_CSR_IRQ -1
#define SYS_TSE_MSGDMA_RX_CSR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SYS_TSE_MSGDMA_RX_CSR_MAX_BURST_COUNT 2
#define SYS_TSE_MSGDMA_RX_CSR_MAX_BYTE 262144
#define SYS_TSE_MSGDMA_RX_CSR_MAX_STRIDE 1
#define SYS_TSE_MSGDMA_RX_CSR_NAME "/dev/sys_tse_msgdma_rx_csr"
#define SYS_TSE_MSGDMA_RX_CSR_PACKET_ENABLE 1
#define SYS_TSE_MSGDMA_RX_CSR_PACKET_ENABLE_DERIVED 1
#define SYS_TSE_MSGDMA_RX_CSR_PREFETCHER_ENABLE 1
#define SYS_TSE_MSGDMA_RX_CSR_PROGRAMMABLE_BURST_ENABLE 0
#define SYS_TSE_MSGDMA_RX_CSR_RESPONSE_PORT 2
#define SYS_TSE_MSGDMA_RX_CSR_SIDEBAND_ENABLE 0
#define SYS_TSE_MSGDMA_RX_CSR_SPAN 32
#define SYS_TSE_MSGDMA_RX_CSR_STRIDE_ENABLE 0
#define SYS_TSE_MSGDMA_RX_CSR_STRIDE_ENABLE_DERIVED 0
#define SYS_TSE_MSGDMA_RX_CSR_TRANSFER_TYPE "Unaligned Accesses"
#define SYS_TSE_MSGDMA_RX_CSR_TYPE "altera_msgdma"


/*
 * sys_tse_msgdma_rx_prefetcher_csr configuration
 *
 */

#define ALT_MODULE_CLASS_sys_tse_msgdma_rx_prefetcher_csr altera_msgdma
#define SYS_TSE_MSGDMA_RX_PREFETCHER_CSR_BASE 0x212480
#define SYS_TSE_MSGDMA_RX_PREFETCHER_CSR_BURST_ENABLE 0
#define SYS_TSE_MSGDMA_RX_PREFETCHER_CSR_BURST_WRAPPING_SUPPORT 0
#define SYS_TSE_MSGDMA_RX_PREFETCHER_CSR_CHANNEL_ENABLE 0
#define SYS_TSE_MSGDMA_RX_PREFETCHER_CSR_CHANNEL_ENABLE_DERIVED 0
#define SYS_TSE_MSGDMA_RX_PREFETCHER_CSR_CHANNEL_WIDTH 8
#define SYS_TSE_MSGDMA_RX_PREFETCHER_CSR_DATA_FIFO_DEPTH 2048
#define SYS_TSE_MSGDMA_RX_PREFETCHER_CSR_DATA_WIDTH 32
#define SYS_TSE_MSGDMA_RX_PREFETCHER_CSR_DESCRIPTOR_FIFO_DEPTH 128
#define SYS_TSE_MSGDMA_RX_PREFETCHER_CSR_DMA_MODE 2
#define SYS_TSE_MSGDMA_RX_PREFETCHER_CSR_ENHANCED_FEATURES 0
#define SYS_TSE_MSGDMA_RX_PREFETCHER_CSR_ERROR_ENABLE 1
#define SYS_TSE_MSGDMA_RX_PREFETCHER_CSR_ERROR_ENABLE_DERIVED 1
#define SYS_TSE_MSGDMA_RX_PREFETCHER_CSR_ERROR_WIDTH 6
#define SYS_TSE_MSGDMA_RX_PREFETCHER_CSR_IRQ 1
#define SYS_TSE_MSGDMA_RX_PREFETCHER_CSR_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SYS_TSE_MSGDMA_RX_PREFETCHER_CSR_MAX_BURST_COUNT 2
#define SYS_TSE_MSGDMA_RX_PREFETCHER_CSR_MAX_BYTE 262144
#define SYS_TSE_MSGDMA_RX_PREFETCHER_CSR_MAX_STRIDE 1
#define SYS_TSE_MSGDMA_RX_PREFETCHER_CSR_NAME "/dev/sys_tse_msgdma_rx_prefetcher_csr"
#define SYS_TSE_MSGDMA_RX_PREFETCHER_CSR_PACKET_ENABLE 1
#define SYS_TSE_MSGDMA_RX_PREFETCHER_CSR_PACKET_ENABLE_DERIVED 1
#define SYS_TSE_MSGDMA_RX_PREFETCHER_CSR_PREFETCHER_ENABLE 1
#define SYS_TSE_MSGDMA_RX_PREFETCHER_CSR_PROGRAMMABLE_BURST_ENABLE 0
#define SYS_TSE_MSGDMA_RX_PREFETCHER_CSR_RESPONSE_PORT 2
#define SYS_TSE_MSGDMA_RX_PREFETCHER_CSR_SIDEBAND_ENABLE 0
#define SYS_TSE_MSGDMA_RX_PREFETCHER_CSR_SPAN 32
#define SYS_TSE_MSGDMA_RX_PREFETCHER_CSR_STRIDE_ENABLE 0
#define SYS_TSE_MSGDMA_RX_PREFETCHER_CSR_STRIDE_ENABLE_DERIVED 0
#define SYS_TSE_MSGDMA_RX_PREFETCHER_CSR_TRANSFER_TYPE "Unaligned Accesses"
#define SYS_TSE_MSGDMA_RX_PREFETCHER_CSR_TYPE "altera_msgdma"


/*
 * sys_tse_msgdma_tx_csr configuration
 *
 */

#define ALT_MODULE_CLASS_sys_tse_msgdma_tx_csr altera_msgdma
#define SYS_TSE_MSGDMA_TX_CSR_BASE 0x212460
#define SYS_TSE_MSGDMA_TX_CSR_BURST_ENABLE 0
#define SYS_TSE_MSGDMA_TX_CSR_BURST_WRAPPING_SUPPORT 0
#define SYS_TSE_MSGDMA_TX_CSR_CHANNEL_ENABLE 0
#define SYS_TSE_MSGDMA_TX_CSR_CHANNEL_ENABLE_DERIVED 0
#define SYS_TSE_MSGDMA_TX_CSR_CHANNEL_WIDTH 8
#define SYS_TSE_MSGDMA_TX_CSR_DATA_FIFO_DEPTH 2048
#define SYS_TSE_MSGDMA_TX_CSR_DATA_WIDTH 32
#define SYS_TSE_MSGDMA_TX_CSR_DESCRIPTOR_FIFO_DEPTH 128
#define SYS_TSE_MSGDMA_TX_CSR_DMA_MODE 1
#define SYS_TSE_MSGDMA_TX_CSR_ENHANCED_FEATURES 0
#define SYS_TSE_MSGDMA_TX_CSR_ERROR_ENABLE 1
#define SYS_TSE_MSGDMA_TX_CSR_ERROR_ENABLE_DERIVED 1
#define SYS_TSE_MSGDMA_TX_CSR_ERROR_WIDTH 1
#define SYS_TSE_MSGDMA_TX_CSR_IRQ -1
#define SYS_TSE_MSGDMA_TX_CSR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SYS_TSE_MSGDMA_TX_CSR_MAX_BURST_COUNT 2
#define SYS_TSE_MSGDMA_TX_CSR_MAX_BYTE 262144
#define SYS_TSE_MSGDMA_TX_CSR_MAX_STRIDE 1
#define SYS_TSE_MSGDMA_TX_CSR_NAME "/dev/sys_tse_msgdma_tx_csr"
#define SYS_TSE_MSGDMA_TX_CSR_PACKET_ENABLE 1
#define SYS_TSE_MSGDMA_TX_CSR_PACKET_ENABLE_DERIVED 1
#define SYS_TSE_MSGDMA_TX_CSR_PREFETCHER_ENABLE 1
#define SYS_TSE_MSGDMA_TX_CSR_PROGRAMMABLE_BURST_ENABLE 0
#define SYS_TSE_MSGDMA_TX_CSR_RESPONSE_PORT 2
#define SYS_TSE_MSGDMA_TX_CSR_SIDEBAND_ENABLE 0
#define SYS_TSE_MSGDMA_TX_CSR_SPAN 32
#define SYS_TSE_MSGDMA_TX_CSR_STRIDE_ENABLE 0
#define SYS_TSE_MSGDMA_TX_CSR_STRIDE_ENABLE_DERIVED 0
#define SYS_TSE_MSGDMA_TX_CSR_TRANSFER_TYPE "Unaligned Accesses"
#define SYS_TSE_MSGDMA_TX_CSR_TYPE "altera_msgdma"


/*
 * sys_tse_msgdma_tx_prefetcher_csr configuration
 *
 */

#define ALT_MODULE_CLASS_sys_tse_msgdma_tx_prefetcher_csr altera_msgdma
#define SYS_TSE_MSGDMA_TX_PREFETCHER_CSR_BASE 0x212440
#define SYS_TSE_MSGDMA_TX_PREFETCHER_CSR_BURST_ENABLE 0
#define SYS_TSE_MSGDMA_TX_PREFETCHER_CSR_BURST_WRAPPING_SUPPORT 0
#define SYS_TSE_MSGDMA_TX_PREFETCHER_CSR_CHANNEL_ENABLE 0
#define SYS_TSE_MSGDMA_TX_PREFETCHER_CSR_CHANNEL_ENABLE_DERIVED 0
#define SYS_TSE_MSGDMA_TX_PREFETCHER_CSR_CHANNEL_WIDTH 8
#define SYS_TSE_MSGDMA_TX_PREFETCHER_CSR_DATA_FIFO_DEPTH 2048
#define SYS_TSE_MSGDMA_TX_PREFETCHER_CSR_DATA_WIDTH 32
#define SYS_TSE_MSGDMA_TX_PREFETCHER_CSR_DESCRIPTOR_FIFO_DEPTH 128
#define SYS_TSE_MSGDMA_TX_PREFETCHER_CSR_DMA_MODE 1
#define SYS_TSE_MSGDMA_TX_PREFETCHER_CSR_ENHANCED_FEATURES 0
#define SYS_TSE_MSGDMA_TX_PREFETCHER_CSR_ERROR_ENABLE 1
#define SYS_TSE_MSGDMA_TX_PREFETCHER_CSR_ERROR_ENABLE_DERIVED 1
#define SYS_TSE_MSGDMA_TX_PREFETCHER_CSR_ERROR_WIDTH 1
#define SYS_TSE_MSGDMA_TX_PREFETCHER_CSR_IRQ 2
#define SYS_TSE_MSGDMA_TX_PREFETCHER_CSR_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SYS_TSE_MSGDMA_TX_PREFETCHER_CSR_MAX_BURST_COUNT 2
#define SYS_TSE_MSGDMA_TX_PREFETCHER_CSR_MAX_BYTE 262144
#define SYS_TSE_MSGDMA_TX_PREFETCHER_CSR_MAX_STRIDE 1
#define SYS_TSE_MSGDMA_TX_PREFETCHER_CSR_NAME "/dev/sys_tse_msgdma_tx_prefetcher_csr"
#define SYS_TSE_MSGDMA_TX_PREFETCHER_CSR_PACKET_ENABLE 1
#define SYS_TSE_MSGDMA_TX_PREFETCHER_CSR_PACKET_ENABLE_DERIVED 1
#define SYS_TSE_MSGDMA_TX_PREFETCHER_CSR_PREFETCHER_ENABLE 1
#define SYS_TSE_MSGDMA_TX_PREFETCHER_CSR_PROGRAMMABLE_BURST_ENABLE 0
#define SYS_TSE_MSGDMA_TX_PREFETCHER_CSR_RESPONSE_PORT 2
#define SYS_TSE_MSGDMA_TX_PREFETCHER_CSR_SIDEBAND_ENABLE 0
#define SYS_TSE_MSGDMA_TX_PREFETCHER_CSR_SPAN 32
#define SYS_TSE_MSGDMA_TX_PREFETCHER_CSR_STRIDE_ENABLE 0
#define SYS_TSE_MSGDMA_TX_PREFETCHER_CSR_STRIDE_ENABLE_DERIVED 0
#define SYS_TSE_MSGDMA_TX_PREFETCHER_CSR_TRANSFER_TYPE "Unaligned Accesses"
#define SYS_TSE_MSGDMA_TX_PREFETCHER_CSR_TYPE "altera_msgdma"

#endif /* __SYSTEM_H_ */
