// qsys_top_intel_niosv_g_0.v

// Generated using ACDS version 25.3 109

`timescale 1 ps / 1 ps
module qsys_top_intel_niosv_g_0 (
		input  wire        clk,                          //                 clk.clk,           Clock Input
		input  wire        reset_reset,                  //               reset.reset,         Reset Input
		input  wire [15:0] platform_irq_rx_irq,          //     platform_irq_rx.irq
		output wire [2:0]  instruction_manager_awsize,   // instruction_manager.awsize
		output wire [7:0]  instruction_manager_awlen,    //                    .awlen
		output wire [1:0]  instruction_manager_awburst,  //                    .awburst
		output wire        instruction_manager_wlast,    //                    .wlast
		output wire [2:0]  instruction_manager_arsize,   //                    .arsize
		output wire [7:0]  instruction_manager_arlen,    //                    .arlen
		output wire [1:0]  instruction_manager_arburst,  //                    .arburst
		input  wire        instruction_manager_rlast,    //                    .rlast
		output wire [31:0] instruction_manager_awaddr,   //                    .awaddr
		output wire [2:0]  instruction_manager_awprot,   //                    .awprot
		output wire        instruction_manager_awvalid,  //                    .awvalid
		input  wire        instruction_manager_awready,  //                    .awready
		output wire [31:0] instruction_manager_wdata,    //                    .wdata
		output wire [3:0]  instruction_manager_wstrb,    //                    .wstrb
		output wire        instruction_manager_wvalid,   //                    .wvalid
		input  wire        instruction_manager_wready,   //                    .wready
		input  wire [1:0]  instruction_manager_bresp,    //                    .bresp
		input  wire        instruction_manager_bvalid,   //                    .bvalid
		output wire        instruction_manager_bready,   //                    .bready
		output wire [31:0] instruction_manager_araddr,   //                    .araddr
		output wire [2:0]  instruction_manager_arprot,   //                    .arprot
		output wire        instruction_manager_arvalid,  //                    .arvalid
		input  wire        instruction_manager_arready,  //                    .arready
		input  wire [31:0] instruction_manager_rdata,    //                    .rdata
		input  wire [1:0]  instruction_manager_rresp,    //                    .rresp
		input  wire        instruction_manager_rvalid,   //                    .rvalid
		output wire        instruction_manager_rready,   //                    .rready
		output wire [2:0]  data_manager_awsize,          //        data_manager.awsize
		output wire [7:0]  data_manager_awlen,           //                    .awlen
		output wire        data_manager_wlast,           //                    .wlast
		output wire [2:0]  data_manager_arsize,          //                    .arsize
		output wire [7:0]  data_manager_arlen,           //                    .arlen
		input  wire        data_manager_rlast,           //                    .rlast
		output wire [31:0] data_manager_awaddr,          //                    .awaddr
		output wire [2:0]  data_manager_awprot,          //                    .awprot
		output wire        data_manager_awvalid,         //                    .awvalid
		input  wire        data_manager_awready,         //                    .awready
		output wire [31:0] data_manager_wdata,           //                    .wdata
		output wire [3:0]  data_manager_wstrb,           //                    .wstrb
		output wire        data_manager_wvalid,          //                    .wvalid
		input  wire        data_manager_wready,          //                    .wready
		input  wire [1:0]  data_manager_bresp,           //                    .bresp
		input  wire        data_manager_bvalid,          //                    .bvalid
		output wire        data_manager_bready,          //                    .bready
		output wire [31:0] data_manager_araddr,          //                    .araddr
		output wire [2:0]  data_manager_arprot,          //                    .arprot
		output wire        data_manager_arvalid,         //                    .arvalid
		input  wire        data_manager_arready,         //                    .arready
		input  wire [31:0] data_manager_rdata,           //                    .rdata
		input  wire [1:0]  data_manager_rresp,           //                    .rresp
		input  wire        data_manager_rvalid,          //                    .rvalid
		output wire        data_manager_rready,          //                    .rready
		input  wire [5:0]  timer_sw_agent_address,       //      timer_sw_agent.address,       The address in the Timer and Software Interrupt Module that the core wants to write to or read from. This is relative to the Timer and Software Interrupt Module base address.
		input  wire [3:0]  timer_sw_agent_byteenable,    //                    .byteenable,    Store byte enable.
		input  wire        timer_sw_agent_read,          //                    .read,          Indicates if the core wants to load from "timer_sw_agent_address" in the Timer and Software Interrupt Module.
		output wire [31:0] timer_sw_agent_readdata,      //                    .readdata,      Load data from the Timer and Software Interrupt Module sent to the core.
		input  wire        timer_sw_agent_write,         //                    .write,         Indicates if the core wants to store to "timer_sw_agent_address" in the Timer and Software Interrupt Module.
		input  wire [31:0] timer_sw_agent_writedata,     //                    .writedata,     Store data to the Timer and Software Interrupt Module sent from the core.
		output wire        timer_sw_agent_waitrequest,   //                    .waitrequest,   Timer and Software Interrupt Module not ready to receive write or read request from the core.
		output wire        timer_sw_agent_readdatavalid, //                    .readdatavalid, Load data valid.
		input  wire [15:0] dm_agent_address,             //            dm_agent.address,       The address in the Debug Module that the core wants to write to or read from. This is relative to the Debug Module base address.
		input  wire        dm_agent_read,                //                    .read,          Indicates if the core wants to load from "dm_agent_address" in the Debug Module.
		output wire [31:0] dm_agent_readdata,            //                    .readdata,      Load data from the Debug Module sent to the core.
		input  wire        dm_agent_write,               //                    .write,         Indicates if the core wants to store to "dm_agent_address" in the Debug Module.
		input  wire [31:0] dm_agent_writedata,           //                    .writedata,     Store data to the Debug Module sent from the core.
		output wire        dm_agent_waitrequest,         //                    .waitrequest,   Debug Module not ready to receive write or read request from the core.
		output wire        dm_agent_readdatavalid        //                    .readdatavalid, Load data valid.
	);

	qsys_top_intel_niosv_g_0_intel_niosv_g_400_iq3fpyq intel_niosv_g_0 (
		.clk                          (clk),                          //   input,   width = 1,                 clk.clk
		.reset_reset                  (reset_reset),                  //   input,   width = 1,               reset.reset
		.platform_irq_rx_irq          (platform_irq_rx_irq),          //   input,  width = 16,     platform_irq_rx.irq
		.instruction_manager_awsize   (instruction_manager_awsize),   //  output,   width = 3, instruction_manager.awsize
		.instruction_manager_awlen    (instruction_manager_awlen),    //  output,   width = 8,                    .awlen
		.instruction_manager_awburst  (instruction_manager_awburst),  //  output,   width = 2,                    .awburst
		.instruction_manager_wlast    (instruction_manager_wlast),    //  output,   width = 1,                    .wlast
		.instruction_manager_arsize   (instruction_manager_arsize),   //  output,   width = 3,                    .arsize
		.instruction_manager_arlen    (instruction_manager_arlen),    //  output,   width = 8,                    .arlen
		.instruction_manager_arburst  (instruction_manager_arburst),  //  output,   width = 2,                    .arburst
		.instruction_manager_rlast    (instruction_manager_rlast),    //   input,   width = 1,                    .rlast
		.instruction_manager_awaddr   (instruction_manager_awaddr),   //  output,  width = 32,                    .awaddr
		.instruction_manager_awprot   (instruction_manager_awprot),   //  output,   width = 3,                    .awprot
		.instruction_manager_awvalid  (instruction_manager_awvalid),  //  output,   width = 1,                    .awvalid
		.instruction_manager_awready  (instruction_manager_awready),  //   input,   width = 1,                    .awready
		.instruction_manager_wdata    (instruction_manager_wdata),    //  output,  width = 32,                    .wdata
		.instruction_manager_wstrb    (instruction_manager_wstrb),    //  output,   width = 4,                    .wstrb
		.instruction_manager_wvalid   (instruction_manager_wvalid),   //  output,   width = 1,                    .wvalid
		.instruction_manager_wready   (instruction_manager_wready),   //   input,   width = 1,                    .wready
		.instruction_manager_bresp    (instruction_manager_bresp),    //   input,   width = 2,                    .bresp
		.instruction_manager_bvalid   (instruction_manager_bvalid),   //   input,   width = 1,                    .bvalid
		.instruction_manager_bready   (instruction_manager_bready),   //  output,   width = 1,                    .bready
		.instruction_manager_araddr   (instruction_manager_araddr),   //  output,  width = 32,                    .araddr
		.instruction_manager_arprot   (instruction_manager_arprot),   //  output,   width = 3,                    .arprot
		.instruction_manager_arvalid  (instruction_manager_arvalid),  //  output,   width = 1,                    .arvalid
		.instruction_manager_arready  (instruction_manager_arready),  //   input,   width = 1,                    .arready
		.instruction_manager_rdata    (instruction_manager_rdata),    //   input,  width = 32,                    .rdata
		.instruction_manager_rresp    (instruction_manager_rresp),    //   input,   width = 2,                    .rresp
		.instruction_manager_rvalid   (instruction_manager_rvalid),   //   input,   width = 1,                    .rvalid
		.instruction_manager_rready   (instruction_manager_rready),   //  output,   width = 1,                    .rready
		.data_manager_awsize          (data_manager_awsize),          //  output,   width = 3,        data_manager.awsize
		.data_manager_awlen           (data_manager_awlen),           //  output,   width = 8,                    .awlen
		.data_manager_wlast           (data_manager_wlast),           //  output,   width = 1,                    .wlast
		.data_manager_arsize          (data_manager_arsize),          //  output,   width = 3,                    .arsize
		.data_manager_arlen           (data_manager_arlen),           //  output,   width = 8,                    .arlen
		.data_manager_rlast           (data_manager_rlast),           //   input,   width = 1,                    .rlast
		.data_manager_awaddr          (data_manager_awaddr),          //  output,  width = 32,                    .awaddr
		.data_manager_awprot          (data_manager_awprot),          //  output,   width = 3,                    .awprot
		.data_manager_awvalid         (data_manager_awvalid),         //  output,   width = 1,                    .awvalid
		.data_manager_awready         (data_manager_awready),         //   input,   width = 1,                    .awready
		.data_manager_wdata           (data_manager_wdata),           //  output,  width = 32,                    .wdata
		.data_manager_wstrb           (data_manager_wstrb),           //  output,   width = 4,                    .wstrb
		.data_manager_wvalid          (data_manager_wvalid),          //  output,   width = 1,                    .wvalid
		.data_manager_wready          (data_manager_wready),          //   input,   width = 1,                    .wready
		.data_manager_bresp           (data_manager_bresp),           //   input,   width = 2,                    .bresp
		.data_manager_bvalid          (data_manager_bvalid),          //   input,   width = 1,                    .bvalid
		.data_manager_bready          (data_manager_bready),          //  output,   width = 1,                    .bready
		.data_manager_araddr          (data_manager_araddr),          //  output,  width = 32,                    .araddr
		.data_manager_arprot          (data_manager_arprot),          //  output,   width = 3,                    .arprot
		.data_manager_arvalid         (data_manager_arvalid),         //  output,   width = 1,                    .arvalid
		.data_manager_arready         (data_manager_arready),         //   input,   width = 1,                    .arready
		.data_manager_rdata           (data_manager_rdata),           //   input,  width = 32,                    .rdata
		.data_manager_rresp           (data_manager_rresp),           //   input,   width = 2,                    .rresp
		.data_manager_rvalid          (data_manager_rvalid),          //   input,   width = 1,                    .rvalid
		.data_manager_rready          (data_manager_rready),          //  output,   width = 1,                    .rready
		.timer_sw_agent_address       (timer_sw_agent_address),       //   input,   width = 6,      timer_sw_agent.address
		.timer_sw_agent_byteenable    (timer_sw_agent_byteenable),    //   input,   width = 4,                    .byteenable
		.timer_sw_agent_read          (timer_sw_agent_read),          //   input,   width = 1,                    .read
		.timer_sw_agent_readdata      (timer_sw_agent_readdata),      //  output,  width = 32,                    .readdata
		.timer_sw_agent_write         (timer_sw_agent_write),         //   input,   width = 1,                    .write
		.timer_sw_agent_writedata     (timer_sw_agent_writedata),     //   input,  width = 32,                    .writedata
		.timer_sw_agent_waitrequest   (timer_sw_agent_waitrequest),   //  output,   width = 1,                    .waitrequest
		.timer_sw_agent_readdatavalid (timer_sw_agent_readdatavalid), //  output,   width = 1,                    .readdatavalid
		.dm_agent_address             (dm_agent_address),             //   input,  width = 16,            dm_agent.address
		.dm_agent_read                (dm_agent_read),                //   input,   width = 1,                    .read
		.dm_agent_readdata            (dm_agent_readdata),            //  output,  width = 32,                    .readdata
		.dm_agent_write               (dm_agent_write),               //   input,   width = 1,                    .write
		.dm_agent_writedata           (dm_agent_writedata),           //   input,  width = 32,                    .writedata
		.dm_agent_waitrequest         (dm_agent_waitrequest),         //  output,   width = 1,                    .waitrequest
		.dm_agent_readdatavalid       (dm_agent_readdatavalid)        //  output,   width = 1,                    .readdatavalid
	);

endmodule
