// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


// megafunction wizard: %ALTDDIO_OUT%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: altddio_out 

// ============================================================
// File Name: rgmii_out4.v
// Megafunction Name(s):
// 			altddio_out
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 6.0 Build 176 04/19/2006 SJ Full Version
// ************************************************************


//Copyright (C) 1991-2006 Altera Corporation
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, Altera MegaCore Function License 
//Agreement, or other applicable license agreement, including, 
//without limitation, that your use is for the sole purpose of 
//programming logic devices manufactured by Altera and sold by 
//Altera or its authorized distributors.  Please refer to the 
//applicable agreement for further details.


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module altera_tse_rgmii_out4 (
	aclr,
	datain_h,
	datain_l,
	outclock,
	dataout);

        parameter DEVICE_FAMILY         = "ARRIAGX";      //  The device family

	input	  aclr;
	input	[3:0]  datain_h;
	input	[3:0]  datain_l;
	input	  outclock;
	output	[3:0]  dataout;

	wire [3:0] sub_wire0;
	wire [3:0] dataout = sub_wire0[3:0];

	generate if (DEVICE_FAMILY != "SUNDANCEMESA") begin
	  altddio_out	altddio_out_component (
				.outclock (outclock),
				.datain_h (datain_h),
				.aclr (aclr),
				.datain_l (datain_l),
				.dataout (sub_wire0),
				.aset (1'b0),
				.oe (1'b1),
				.outclocken (1'b1));
	  defparam
		altddio_out_component.extend_oe_disable = "UNUSED",
		altddio_out_component.intended_device_family = "Stratix II",
		altddio_out_component.lpm_type = "altddio_out",
		altddio_out_component.oe_reg = "UNUSED",
		altddio_out_component.width = 4;
        end
        else begin
          tennm_ph2_ddio_out #(
               .mode("MODE_DDR"),
               //.asclr_ena("ASCLR_ENA_NONE")
               .sclr_ena("SCLR_ENA_NONE"),
               .asclr_ena("ASCLR_ENA_CLEAR")
          ) tennm_ddio_out0 (
               .ena(1'b1),
               .areset(~aclr),
               .sreset(1'b0),
               .dataout(sub_wire0[0]),
               .datainlo(datain_l[0]),
               .datainhi(datain_h[0]),
               .clk(outclock) // this may use tx_clk for better delay than div2 clk
          );

          tennm_ph2_ddio_out #(
               .mode("MODE_DDR"),
             //  .asclr_ena("ASCLR_ENA_NONE")
               .sclr_ena("SCLR_ENA_NONE"),
               .asclr_ena("ASCLR_ENA_CLEAR")
          ) tennm_ddio_out1 (
               .ena(1'b1),
               .areset(~aclr),
               .sreset(1'b0),
               .dataout(sub_wire0[1]),
               .datainlo(datain_l[1]),
               .datainhi(datain_h[1]),
               .clk(outclock) // this may use tx_clk for better delay than div2 clk
          );

          tennm_ph2_ddio_out #(
               .mode("MODE_DDR"),
              // .asclr_ena("ASCLR_ENA_NONE")
               .sclr_ena("SCLR_ENA_NONE"),
               .asclr_ena("ASCLR_ENA_CLEAR")
          ) tennm_ddio_out2 (
               .ena(1'b1),
               .areset(~aclr),
               .sreset(1'b0),
               .dataout(sub_wire0[2]),
               .datainlo(datain_l[2]),
               .datainhi(datain_h[2]),
               .clk(outclock) // this may use tx_clk for better delay than div2 clk
          );

          tennm_ph2_ddio_out #(
               .mode("MODE_DDR"),
              // .asclr_ena("ASCLR_ENA_NONE")
               .sclr_ena("SCLR_ENA_NONE"),
               .asclr_ena("ASCLR_ENA_CLEAR")
          ) tennm_ddio_out3 (
               .ena(1'b1),
               .areset(~aclr),
               .sreset(1'b0), 
               .dataout(sub_wire0[3]),
               .datainlo(datain_l[3]),
               .datainhi(datain_h[3]),
               .clk(outclock) // this may use tx_clk for better delay than div2 clk
          );
        end
        endgenerate

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: ARESET_MODE NUMERIC "0"
// Retrieval info: PRIVATE: CLKEN NUMERIC "0"
// Retrieval info: PRIVATE: EXTEND_OE_DISABLE NUMERIC "0"
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Stratix II"
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Stratix II"
// Retrieval info: PRIVATE: OE NUMERIC "0"
// Retrieval info: PRIVATE: OE_REG NUMERIC "0"
// Retrieval info: PRIVATE: POWER_UP_HIGH NUMERIC "0"
// Retrieval info: PRIVATE: WIDTH NUMERIC "4"
// Retrieval info: CONSTANT: EXTEND_OE_DISABLE STRING "UNUSED"
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Stratix II"
// Retrieval info: CONSTANT: LPM_TYPE STRING "altddio_out"
// Retrieval info: CONSTANT: OE_REG STRING "UNUSED"
// Retrieval info: CONSTANT: WIDTH NUMERIC "4"
// Retrieval info: USED_PORT: aclr 0 0 0 0 INPUT GND aclr
// Retrieval info: USED_PORT: datain_h 0 0 4 0 INPUT NODEFVAL datain_h[3..0]
// Retrieval info: USED_PORT: datain_l 0 0 4 0 INPUT NODEFVAL datain_l[3..0]
// Retrieval info: USED_PORT: dataout 0 0 4 0 OUTPUT NODEFVAL dataout[3..0]
// Retrieval info: USED_PORT: outclock 0 0 0 0 INPUT_CLK_EXT NODEFVAL outclock
// Retrieval info: CONNECT: @datain_h 0 0 4 0 datain_h 0 0 4 0
// Retrieval info: CONNECT: @datain_l 0 0 4 0 datain_l 0 0 4 0
// Retrieval info: CONNECT: dataout 0 0 4 0 @dataout 0 0 4 0
// Retrieval info: CONNECT: @outclock 0 0 0 0 outclock 0 0 0 0
// Retrieval info: CONNECT: @aclr 0 0 0 0 aclr 0 0 0 0
// Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
// Retrieval info: GEN_FILE: TYPE_NORMAL rgmii_out4.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL rgmii_out4.ppf TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL rgmii_out4.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL rgmii_out4.cmp FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL rgmii_out4.bsf TRUE FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL rgmii_out4_inst.v FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL rgmii_out4_bb.v TRUE
`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "O9RNUzBGi1MUBLEZwJgMVrF7NbqhR0frCxdzR4bl83YxcdShSICP6gn7DgXB5Wj0Geho2ojJWRyULSlAIGz85zR8OvNMA0pLv8TOlniXS0jjVXGztQAyUJSYyDK0E10JjiEkmryQPAxvtvS997m9ZkkEwE8aH3k3eKlS9+aYYR3u8ZETUkJnL6h49N3PqQYRDFIBz4TzCxkPjjdV4tZnq25ZxRw5j5HEDtVDwCwTIp/+M3SeKhSwrUWFb0QeaF1FgqmGV/kbpduT28NoXluxifHqz3CMeaq1STkXlekYtK2Yue6b6rwDGVReARJD6sZwSJb87HC8TZuvrFW2O68b4i+LdR6hyi6jku3RGpNhpiuu3coLiUZayha0/OuwFX3aTTKsvHLGTOcNIwHkahngVJ70T+rvJHI9SPhvYe7ImLdQSyACmr7E90F9C4HKEqEDTuA8x+e6Rw89I00xkMUwvYqxvadW4Mqw6kQl9qsol6w0F9VrZRi1fUNqUjyvY28N4Mr3cS8HmqneIfwAY4YA1DgF+jadW/SqW8K88ezvknAO/mMOpKgmGaW4qcs+eH9OCG6eL92ouL/ddgDycxLV80KLDWNHJIhXFA3YnC2HhWTyOphUdASMYTo1Yr9kj1J0wwaO9rKjilU/ROP2byIgUQemUgJyz+Qs5zCgNdMHbfluA+XJP3eAC0gh+QJ2QHAof2kTP1cewIbtOI7uYUkjqXe9neB40aGPbsbVvRHIl0VGAOGpCkuN5EDZ065spkMQwF3SfdvYXsParvjTAvet3Irj4lcjKqCw1NaDxIDKH6hfcalYzh0UbJ3AgIAo6DfFMONsg3a3y9wY47iyWfXVRz/8DfC/p69sIMq9N5F8hsLU57NZEUpFxetyYdLmcMWsAuRM5GwCp6Q2NA+J8zu7OKRENcznttF7NeLmXeUSMDKKroWtS1OASGLeWmbeuxnwRbylxXqH9s7MhXFWGwhBaYqLTqjs7xn8M5/6Z0dmfutVtcFMQvv+5IK6/5t9CrtH"
`endif