// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


// megafunction wizard: %ALTDDIO_IN%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: altddio_in 

// ============================================================
// File Name: rgmii_in4.v
// Megafunction Name(s):
// 			altddio_in
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 6.0 Build 176 04/19/2006 SJ Full Version
// ************************************************************


//Copyright (C) 1991-2006 Altera Corporation
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, Altera MegaCore Function License 
//Agreement, or other applicable license agreement, including, 
//without limitation, that your use is for the sole purpose of 
//programming logic devices manufactured by Altera and sold by 
//Altera or its authorized distributors.  Please refer to the 
//applicable agreement for further details.


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module altera_tse_rgmii_in4 (
	aclr,
	datain,
	inclock,
	dataout_h,
	dataout_l);

        parameter DEVICE_FAMILY         = "ARRIAGX";      //  The device family

	input	  aclr;
	input	[3:0]  datain;
	input	  inclock;
	output	[3:0]  dataout_h;
	output	[3:0]  dataout_l;

	wire [3:0] sub_wire0;
	wire [3:0] sub_wire1;
	wire [3:0] p2c_1;
	wire [3:0] p2c_0;
	wire [3:0] dataout_h = sub_wire0[3:0];
	wire [3:0] dataout_l = sub_wire1[3:0];

	generate if (DEVICE_FAMILY != "SUNDANCEMESA") begin
 	  altddio_in	altddio_in_component (
 				.datain (datain),
 				.inclock (inclock),
 				.aclr (aclr),
 				.dataout_h (sub_wire0),
 				.dataout_l (sub_wire1),
 				.aset (1'b0),
 				.inclocken (1'b1));
 	defparam
 		altddio_in_component.intended_device_family = "Stratix II",
 		altddio_in_component.invert_input_clocks = "OFF",
 		altddio_in_component.lpm_type = "altddio_in",
 		altddio_in_component.width = 4;

	end
	else begin
          tennm_ph2_ddio_in #(
                //.mode("MODE_DDR"),
                .mode("MODE_DDR_W_DLY"),
                .sclr_ena("SCLR_ENA_NONE"),
                .asclr_ena("ASCLR_ENA_NONE")
                ) tennm_ddio_in0 (
                .ena(1'b1),
                .areset(1'b1),
                .sreset(1'b0),
                .datain(datain[0]),
                .regoutlo(p2c_1[0]),
                .regouthi(p2c_0[0]),
                .clk(inclock)
                );
			tennm_p2c_pipe_reg p2c_pipe_reg0 (
		               .d(p2c_1[0]),
		               .clk(inclock),
		               .rst(),
		               .q(sub_wire1[0])
           );
			tennm_p2c_pipe_reg p2c_pipe_reg1 (
		               .d(p2c_0[0]),
		               .clk(inclock),
		               .rst(),
		               .q(sub_wire0[0])
           );  
          tennm_ph2_ddio_in #(
                //.mode("MODE_DDR"),
                .mode("MODE_DDR_W_DLY"),
                .sclr_ena("SCLR_ENA_NONE"),
                .asclr_ena("ASCLR_ENA_NONE")
                ) tennm_ddio_in1 (
                .ena(1'b1),
                .areset(1'b1),
                .sreset(1'b0),
                .datain(datain[1]),
                .regoutlo(p2c_1[1]),
                .regouthi(p2c_0[1]),
                .clk(inclock)
                );
			tennm_p2c_pipe_reg p2c_pipe_reg2 (
		               .d(p2c_1[1]),
		               .clk(inclock),
		               .rst(),
		               .q(sub_wire1[1])
           );
			tennm_p2c_pipe_reg p2c_pipe_reg3 (
		               .d(p2c_0[1]),
		               .clk(inclock),
		               .rst(),
		               .q(sub_wire0[1])
           );
          tennm_ph2_ddio_in #(
               // .mode("MODE_DDR"),
                .mode("MODE_DDR_W_DLY"),
                .sclr_ena("SCLR_ENA_NONE"),
                .asclr_ena("ASCLR_ENA_NONE")
                ) tennm_ddio_in2 (
                .ena(1'b1),
                .areset(1'b1),
                .sreset(1'b0),
                .datain(datain[2]),
                .regoutlo(p2c_1[2]),
                .regouthi(p2c_0[2]),
                .clk(inclock)
                );
			tennm_p2c_pipe_reg p2c_pipe_reg4 (
		               .d(p2c_1[2]),
		               .clk(inclock),
		               .rst(),
		               .q(sub_wire1[2])
           );
			tennm_p2c_pipe_reg p2c_pipe_reg5 (
		               .d(p2c_0[2]),
		               .clk(inclock),
		               .rst(),
		               .q(sub_wire0[2])
           );
          tennm_ph2_ddio_in #(
               // .mode("MODE_DDR"),
                .mode("MODE_DDR_W_DLY"),
                .sclr_ena("SCLR_ENA_NONE"),
                .asclr_ena("ASCLR_ENA_NONE")
                ) tennm_ddio_in3 (
                .ena(1'b1),
                .areset(1'b1),
                .sreset(1'b0),
                .datain(datain[3]),
                .regoutlo(p2c_1[3]),
                .regouthi(p2c_0[3]),
                .clk(inclock)
                );
			tennm_p2c_pipe_reg p2c_pipe_reg6 (
		               .d(p2c_1[3]),
		               .clk(inclock),
		               .rst(),
		               .q(sub_wire1[3])
           );
			tennm_p2c_pipe_reg p2c_pipe_reg7 (
		               .d(p2c_0[3]),
		               .clk(inclock),
		               .rst(),
		               .q(sub_wire0[3])
           );
        end
        endgenerate

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: ARESET_MODE NUMERIC "0"
// Retrieval info: PRIVATE: CLKEN NUMERIC "0"
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Stratix II"
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Stratix II"
// Retrieval info: PRIVATE: INVERT_INPUT_CLOCKS NUMERIC "0"
// Retrieval info: PRIVATE: POWER_UP_HIGH NUMERIC "0"
// Retrieval info: PRIVATE: WIDTH NUMERIC "4"
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Stratix II"
// Retrieval info: CONSTANT: INVERT_INPUT_CLOCKS STRING "OFF"
// Retrieval info: CONSTANT: LPM_TYPE STRING "altddio_in"
// Retrieval info: CONSTANT: WIDTH NUMERIC "4"
// Retrieval info: USED_PORT: aclr 0 0 0 0 INPUT GND aclr
// Retrieval info: USED_PORT: datain 0 0 4 0 INPUT NODEFVAL datain[3..0]
// Retrieval info: USED_PORT: dataout_h 0 0 4 0 OUTPUT NODEFVAL dataout_h[3..0]
// Retrieval info: USED_PORT: dataout_l 0 0 4 0 OUTPUT NODEFVAL dataout_l[3..0]
// Retrieval info: USED_PORT: inclock 0 0 0 0 INPUT_CLK_EXT NODEFVAL inclock
// Retrieval info: CONNECT: @datain 0 0 4 0 datain 0 0 4 0
// Retrieval info: CONNECT: dataout_h 0 0 4 0 @dataout_h 0 0 4 0
// Retrieval info: CONNECT: dataout_l 0 0 4 0 @dataout_l 0 0 4 0
// Retrieval info: CONNECT: @inclock 0 0 0 0 inclock 0 0 0 0
// Retrieval info: CONNECT: @aclr 0 0 0 0 aclr 0 0 0 0
// Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
// Retrieval info: GEN_FILE: TYPE_NORMAL rgmii_in4.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL rgmii_in4.ppf TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL rgmii_in4.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL rgmii_in4.cmp FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL rgmii_in4.bsf TRUE FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL rgmii_in4_inst.v FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL rgmii_in4_bb.v TRUE
`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "O9RNUzBGi1MUBLEZwJgMVrF7NbqhR0frCxdzR4bl83YxcdShSICP6gn7DgXB5Wj0Geho2ojJWRyULSlAIGz85zR8OvNMA0pLv8TOlniXS0jjVXGztQAyUJSYyDK0E10JjiEkmryQPAxvtvS997m9ZkkEwE8aH3k3eKlS9+aYYR3u8ZETUkJnL6h49N3PqQYRDFIBz4TzCxkPjjdV4tZnq25ZxRw5j5HEDtVDwCwTIp/lC9d0PA3Rqxbxcd2HtMKGfioBnNZSRge+NOwJesNx3XfHjQxU3Z1vj5vD94MNspFGS88kAErZVm1lXe8soFIvXfEcsNMNMPkN8HDisMf9TDb1/gfYDmsdd9AbZpdN0I4MtZrqEWIziiO+V6CxEmzz9xwyOCQHMg61QDFjLJ5WPju71syqm7E5UJfwu2LzX4yGIb16yJKDn4duIVFkZy5D4h9B8Kvl6T3i/ll+uF9GLwjBQZEGOlODUR3CuV92NT67tzZE25DlTFZW2ZsseYeOElvUa4WyeWo07V/f7A75ZDWzsnF3Ek0xO6rRCE1iTCsfTGhaf4QjS4Eg4UpgKfNJqIhEphZ3Pj9/vy8id3bIx+7e5SvKJAKLMCl33LdyHaM2Tesze4K1gzfJQJK5O3K8nbLMj0T0sv5vqV/r1rEm8EbkRAydzZNL8ZHcCal5EWctU8ETlNxW/RFZRnZn9MPnHXwyfHg0hJ0Bpf74000BYKA9d7cD9GBF7A0X+vnD7z8fpm1HT9ZVedNEjB2wQrdW3nB6fMUFz/S6JHcAlGHsVmx7mOgAIgsJ3eKEMXkIH5+pODxOFKPpYlnIyeF34XkmtXhh8SYm65jdJUgygd/aqEoR4vnWLE2mxcISJO/E61bpaUcYduUqGKQIycskNSX4vMI8X5Oq9dLmFiDjzkTL8Exztxjk/o9v/TIPVkNp13YGKPsyN1CvRzKZup1UsPf8N2BpsLXZAa98qkyerQOUqtPM7APoPIlvMMplAWZVwDpt4sK/JjKgeP7cbrBku2xC"
`endif