// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


// megafunction wizard: %ALTDDIO_IN%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: altddio_in 

// ============================================================
// File Name: rgmii_in1.v
// Megafunction Name(s):
// 			altddio_in
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 6.0 Build 176 04/19/2006 SJ Full Version
// ************************************************************


//Copyright (C) 1991-2006 Altera Corporation
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, Altera MegaCore Function License 
//Agreement, or other applicable license agreement, including, 
//without limitation, that your use is for the sole purpose of 
//programming logic devices manufactured by Altera and sold by 
//Altera or its authorized distributors.  Please refer to the 
//applicable agreement for further details.


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module altera_tse_rgmii_in1 (
	aclr,
	datain,
	inclock,
	dataout_h,
	dataout_l);

        parameter DEVICE_FAMILY         = "ARRIAGX";      //  The device family

	input	  aclr;
	input	  datain;
	input	  inclock;
	output	  dataout_h;
	output	  dataout_l;

	wire [0:0] sub_wire0;
	wire [0:0] sub_wire2;
	wire [0:0] p2c_0;
	wire [0:0] p2c_2;
	wire [0:0] sub_wire1 = sub_wire0[0:0];
	wire  dataout_h = sub_wire1;
	wire [0:0] sub_wire3 = sub_wire2[0:0];
	wire  dataout_l = sub_wire3;
	wire  sub_wire4 = datain;
	wire  sub_wire5 = sub_wire4;

	generate if (DEVICE_FAMILY != "SUNDANCEMESA") begin
	  altddio_in	altddio_in_component (
				.datain (sub_wire5),
				.inclock (inclock),
				.aclr (aclr),
				.dataout_h (sub_wire0),
				.dataout_l (sub_wire2),
				.aset (1'b0),
				.inclocken (1'b1));
	defparam
		altddio_in_component.intended_device_family = "Stratix II",
		altddio_in_component.invert_input_clocks = "OFF",
		altddio_in_component.lpm_type = "altddio_in",
		altddio_in_component.width = 1;

	end
	else begin
          tennm_ph2_ddio_in #(
              //  .mode("MODE_DDR"),
                .mode("MODE_DDR_W_DLY"),
                .sclr_ena("SCLR_ENA_NONE"),
                .asclr_ena("ASCLR_ENA_NONE")
                ) tennm_ddio_in (
                .ena(1'b1),
                .areset(1'b1),
                .sreset(1'b0),
                .datain(sub_wire5),
                .regoutlo(p2c_2),
                .regouthi(p2c_0),
                .clk(inclock)
                );
					 
			tennm_p2c_pipe_reg p2c_pipe_reg0 (
		               .d(p2c_2),
		               .clk(inclock),
		               .rst(),
		               .q(sub_wire2)
           );
			tennm_p2c_pipe_reg p2c_pipe_reg1 (
		               .d(p2c_0),
		               .clk(inclock),
		               .rst(),
		               .q(sub_wire0)
           );
	end
        endgenerate

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: ARESET_MODE NUMERIC "0"
// Retrieval info: PRIVATE: CLKEN NUMERIC "0"
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Stratix II"
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Stratix II"
// Retrieval info: PRIVATE: INVERT_INPUT_CLOCKS NUMERIC "0"
// Retrieval info: PRIVATE: POWER_UP_HIGH NUMERIC "0"
// Retrieval info: PRIVATE: WIDTH NUMERIC "1"
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Stratix II"
// Retrieval info: CONSTANT: INVERT_INPUT_CLOCKS STRING "OFF"
// Retrieval info: CONSTANT: LPM_TYPE STRING "altddio_in"
// Retrieval info: CONSTANT: WIDTH NUMERIC "1"
// Retrieval info: USED_PORT: aclr 0 0 0 0 INPUT GND aclr
// Retrieval info: USED_PORT: datain 0 0 0 0 INPUT NODEFVAL datain
// Retrieval info: USED_PORT: dataout_h 0 0 0 0 OUTPUT NODEFVAL dataout_h
// Retrieval info: USED_PORT: dataout_l 0 0 0 0 OUTPUT NODEFVAL dataout_l
// Retrieval info: USED_PORT: inclock 0 0 0 0 INPUT_CLK_EXT NODEFVAL inclock
// Retrieval info: CONNECT: @datain 0 0 1 0 datain 0 0 0 0
// Retrieval info: CONNECT: dataout_h 0 0 0 0 @dataout_h 0 0 1 0
// Retrieval info: CONNECT: dataout_l 0 0 0 0 @dataout_l 0 0 1 0
// Retrieval info: CONNECT: @inclock 0 0 0 0 inclock 0 0 0 0
// Retrieval info: CONNECT: @aclr 0 0 0 0 aclr 0 0 0 0
// Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
// Retrieval info: GEN_FILE: TYPE_NORMAL rgmii_in1.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL rgmii_in1.ppf TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL rgmii_in1.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL rgmii_in1.cmp FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL rgmii_in1.bsf TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL rgmii_in1_inst.v FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL rgmii_in1_bb.v TRUE
`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "O9RNUzBGi1MUBLEZwJgMVrF7NbqhR0frCxdzR4bl83YxcdShSICP6gn7DgXB5Wj0Geho2ojJWRyULSlAIGz85zR8OvNMA0pLv8TOlniXS0jjVXGztQAyUJSYyDK0E10JjiEkmryQPAxvtvS997m9ZkkEwE8aH3k3eKlS9+aYYR3u8ZETUkJnL6h49N3PqQYRDFIBz4TzCxkPjjdV4tZnq25ZxRw5j5HEDtVDwCwTIp/dBgTWigalTC3pixo/ecQf22w86JisXYecr38TrGJE7ZLBTpGF9gAVRAX5q0JcxMS/uhnX7hdZsman8UEmeVMjPS+CzE2ymjEeQfIvHtIA9slnvZULMZFSWreOeK/yAj6xlr1rLiovNF3nHBnbbMqwdSxvaGFSgXDE4m7HGTkqUvpHhmapFex6labwpFHPCuBJzyrRAGArq4LOFV4xELCkoPZi+FNpNhYit+iQlVgljtkcrjiZLthYcI+CLP09hPTNyaSH+AfVLKiU8U/wORyX0NZfsds5ocKoCsA9woDcN3GurjquOQtT5eKu2dQ/2vhRurY37vS7xM9XSusNbZ4hqt4C89Vvcb4nuWfN3E08Pp9KIMRfF/9L3DmvSfED2vC9R8Zqr1FTv/3xi35+vrQ+OdRzeR0/EzR24GT6g7aVo1Oc71fUF8kIHpVGs1rLoipn8dstOxASfiIEqWPdozHJrj/Hn8SxxNCXX0JiJmaWf90XE4JULnio/c7FTKsoCES4NUlPDzCL4ypsbjHmdKhjNt2NBhf4gnXZeOdnd9CFirrO49kCVVoq297g4/f3ZoLvj6oN25Di/xN+XFnBlspOCDdxGYAV3CZN9XWroK1XinE4j+pbeAIR0/Xzqf5BMJR/tL4QmqaFZPdA55DrFTIrWgwFOLI+MstBkp1yS9vZISRfHRzeSvKtbc8hLiGAV6OlS99T6SyR4bsiTGYf4AHIWjcPnUUgIq5C8RCdUnu4TQotdTieDOmYhYiBCTVvO+e3RgogHBXPnSYxXmbzf25M"
`endif