// qsys_top_msgdma_0_altera_msgdma_1932_k7ydxky.v

// This file was auto-generated from altera_msgdma_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 25.3 109

`timescale 1 ps / 1 ps
module qsys_top_msgdma_0_altera_msgdma_1932_k7ydxky (
		input  wire        clock_clk,                                  //                   clock.clk,               Clock Input
		input  wire        reset_n_reset_n,                            //                 reset_n.reset_n,           Reset Input
		input  wire [31:0] csr_writedata,                              //                     csr.writedata
		input  wire        csr_write,                                  //                        .write
		input  wire [3:0]  csr_byteenable,                             //                        .byteenable
		output wire [31:0] csr_readdata,                               //                        .readdata
		input  wire        csr_read,                                   //                        .read
		input  wire [2:0]  csr_address,                                //                        .address
		output wire [31:0] descriptor_read_master_address,             //  descriptor_read_master.address
		output wire        descriptor_read_master_read,                //                        .read
		input  wire [31:0] descriptor_read_master_readdata,            //                        .readdata
		input  wire        descriptor_read_master_waitrequest,         //                        .waitrequest
		input  wire        descriptor_read_master_readdatavalid,       //                        .readdatavalid
		output wire [31:0] descriptor_write_master_address,            // descriptor_write_master.address
		output wire        descriptor_write_master_write,              //                        .write
		output wire [3:0]  descriptor_write_master_byteenable,         //                        .byteenable
		output wire [31:0] descriptor_write_master_writedata,          //                        .writedata
		input  wire        descriptor_write_master_waitrequest,        //                        .waitrequest
		input  wire [1:0]  descriptor_write_master_response,           //                        .response
		input  wire        descriptor_write_master_writeresponsevalid, //                        .writeresponsevalid
		input  wire [2:0]  prefetcher_csr_address,                     //          prefetcher_csr.address
		input  wire        prefetcher_csr_read,                        //                        .read
		input  wire        prefetcher_csr_write,                       //                        .write
		input  wire [31:0] prefetcher_csr_writedata,                   //                        .writedata
		output wire [31:0] prefetcher_csr_readdata,                    //                        .readdata
		output wire        csr_irq_irq,                                //                 csr_irq.irq
		output wire [31:0] mm_read_address,                            //                 mm_read.address
		output wire        mm_read_read,                               //                        .read
		output wire [3:0]  mm_read_byteenable,                         //                        .byteenable
		input  wire [31:0] mm_read_readdata,                           //                        .readdata
		input  wire        mm_read_waitrequest,                        //                        .waitrequest
		input  wire        mm_read_readdatavalid,                      //                        .readdatavalid
		output wire [31:0] st_source_data,                             //               st_source.data
		output wire        st_source_valid,                            //                        .valid
		input  wire        st_source_ready,                            //                        .ready
		output wire        st_source_startofpacket,                    //                        .startofpacket
		output wire        st_source_endofpacket,                      //                        .endofpacket
		output wire [1:0]  st_source_empty,                            //                        .empty
		output wire        st_source_error                             //                        .error
	);

	wire          prefetcher_internal_descriptor_write_dispatcher_source_valid; // prefetcher_internal:st_src_descr_valid -> dispatcher_internal:snk_descriptor_valid
	wire  [127:0] prefetcher_internal_descriptor_write_dispatcher_source_data;  // prefetcher_internal:st_src_descr_data -> dispatcher_internal:snk_descriptor_data
	wire          prefetcher_internal_descriptor_write_dispatcher_source_ready; // dispatcher_internal:snk_descriptor_ready -> prefetcher_internal:st_src_descr_ready
	wire          dispatcher_internal_response_source_valid;                    // dispatcher_internal:src_response_valid -> prefetcher_internal:st_snk_valid
	wire  [255:0] dispatcher_internal_response_source_data;                     // dispatcher_internal:src_response_data -> prefetcher_internal:st_snk_data
	wire          dispatcher_internal_response_source_ready;                    // prefetcher_internal:st_snk_ready -> dispatcher_internal:src_response_ready
	wire          dispatcher_internal_read_command_source_valid;                // dispatcher_internal:src_read_master_valid -> read_mstr_internal:snk_command_valid
	wire  [255:0] dispatcher_internal_read_command_source_data;                 // dispatcher_internal:src_read_master_data -> read_mstr_internal:snk_command_data
	wire          dispatcher_internal_read_command_source_ready;                // read_mstr_internal:snk_command_ready -> dispatcher_internal:src_read_master_ready
	wire          read_mstr_internal_response_source_valid;                     // read_mstr_internal:src_response_valid -> dispatcher_internal:snk_read_master_valid
	wire  [255:0] read_mstr_internal_response_source_data;                      // read_mstr_internal:src_response_data -> dispatcher_internal:snk_read_master_data
	wire          read_mstr_internal_response_source_ready;                     // dispatcher_internal:snk_read_master_ready -> read_mstr_internal:src_response_ready

	dispatcher #(
		.DEVICE_FAMILY                 ("Agilex 5"),
		.PREFETCHER_USE_CASE           (1),
		.MODE                          (1),
		.RESPONSE_PORT                 (1),
		.DESCRIPTOR_INTERFACE          (1),
		.DESCRIPTOR_FIFO_DEPTH         (128),
		.ENHANCED_FEATURES             (0),
		.DESCRIPTOR_WIDTH              (128),
		.DESCRIPTOR_BYTEENABLE_WIDTH   (16),
		.DATA_WIDTH_DERIVED            (2),
		.DATA_FIFO_DEPTH_DERIVED       (7),
		.MAX_BYTE_DERIVED              (8),
		.TRANSFER_TYPE_DERIVED         (2),
		.SIDEBAND_ENABLE               (0),
		.BURST_ENABLE                  (0),
		.MAX_BURST_COUNT_DERIVED       (0),
		.BURST_WRAPPING_SUPPORT        (0),
		.STRIDE_ENABLE_DERIVED         (0),
		.MAX_STRIDE_DERIVED            (0),
		.PROGRAMMABLE_BURST_ENABLE     (0),
		.CHANNEL_ENABLE                (0),
		.CHANNEL_WIDTH_DERIVED         (7),
		.ERROR_ENABLE                  (1),
		.ERROR_WIDTH_DERIVED           (0),
		.PACKET_ENABLE                 (1),
		.DESCRIPTOR_FIFO_DEPTH_DERIVED (4)
	) dispatcher_internal (
		.clk                     (clock_clk),                                                                                                                                                                                                                                                             //   input,    width = 1,               clock.clk
		.reset                   (~reset_n_reset_n),                                                                                                                                                                                                                                                      //   input,    width = 1,         clock_reset.reset
		.csr_writedata           (csr_writedata),                                                                                                                                                                                                                                                         //   input,   width = 32,                 CSR.writedata
		.csr_write               (csr_write),                                                                                                                                                                                                                                                             //   input,    width = 1,                    .write
		.csr_byteenable          (csr_byteenable),                                                                                                                                                                                                                                                        //   input,    width = 4,                    .byteenable
		.csr_readdata            (csr_readdata),                                                                                                                                                                                                                                                          //  output,   width = 32,                    .readdata
		.csr_read                (csr_read),                                                                                                                                                                                                                                                              //   input,    width = 1,                    .read
		.csr_address             (csr_address),                                                                                                                                                                                                                                                           //   input,    width = 3,                    .address
		.src_response_data       (dispatcher_internal_response_source_data),                                                                                                                                                                                                                              //  output,  width = 256,     Response_Source.data
		.src_response_valid      (dispatcher_internal_response_source_valid),                                                                                                                                                                                                                             //  output,    width = 1,                    .valid
		.src_response_ready      (dispatcher_internal_response_source_ready),                                                                                                                                                                                                                             //   input,    width = 1,                    .ready
		.snk_descriptor_data     (prefetcher_internal_descriptor_write_dispatcher_source_data),                                                                                                                                                                                                           //   input,  width = 128,     Descriptor_Sink.data
		.snk_descriptor_valid    (prefetcher_internal_descriptor_write_dispatcher_source_valid),                                                                                                                                                                                                          //   input,    width = 1,                    .valid
		.snk_descriptor_ready    (prefetcher_internal_descriptor_write_dispatcher_source_ready),                                                                                                                                                                                                          //  output,    width = 1,                    .ready
		.src_read_master_data    (dispatcher_internal_read_command_source_data),                                                                                                                                                                                                                          //  output,  width = 256, Read_Command_Source.data
		.src_read_master_valid   (dispatcher_internal_read_command_source_valid),                                                                                                                                                                                                                         //  output,    width = 1,                    .valid
		.src_read_master_ready   (dispatcher_internal_read_command_source_ready),                                                                                                                                                                                                                         //   input,    width = 1,                    .ready
		.snk_read_master_data    (read_mstr_internal_response_source_data),                                                                                                                                                                                                                               //   input,  width = 256,  Read_Response_Sink.data
		.snk_read_master_valid   (read_mstr_internal_response_source_valid),                                                                                                                                                                                                                              //   input,    width = 1,                    .valid
		.snk_read_master_ready   (read_mstr_internal_response_source_ready),                                                                                                                                                                                                                              //  output,    width = 1,                    .ready
		.descriptor_write        (1'b0),                                                                                                                                                                                                                                                                  // (terminated),                                   
		.descriptor_waitrequest  (),                                                                                                                                                                                                                                                                      // (terminated),                                   
		.descriptor_writedata    (128'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000),                                                                                                                                 // (terminated),                                   
		.descriptor_byteenable   (16'b0000000000000000),                                                                                                                                                                                                                                                  // (terminated),                                   
		.mm_response_waitrequest (),                                                                                                                                                                                                                                                                      // (terminated),                                   
		.mm_response_byteenable  (4'b0000),                                                                                                                                                                                                                                                               // (terminated),                                   
		.mm_response_address     (1'b0),                                                                                                                                                                                                                                                                  // (terminated),                                   
		.mm_response_readdata    (),                                                                                                                                                                                                                                                                      // (terminated),                                   
		.mm_response_read        (1'b0),                                                                                                                                                                                                                                                                  // (terminated),                                   
		.src_write_master_data   (),                                                                                                                                                                                                                                                                      // (terminated),                                   
		.src_write_master_valid  (),                                                                                                                                                                                                                                                                      // (terminated),                                   
		.src_write_master_ready  (1'b0),                                                                                                                                                                                                                                                                  // (terminated),                                   
		.snk_write_master_data   (256'b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000), // (terminated),                                   
		.snk_write_master_valid  (1'b0),                                                                                                                                                                                                                                                                  // (terminated),                                   
		.snk_write_master_ready  (),                                                                                                                                                                                                                                                                      // (terminated),                                   
		.csr_irq                 ()                                                                                                                                                                                                                                                                       // (terminated),                                   
	);

	altera_msgdma_prefetcher #(
		.DEVICE_FAMILY              ("Agilex 5"),
		.ENHANCED_FEATURES          (0),
		.SIDEBAND_ENABLE            (0),
		.ENABLE_READ_BURST          (0),
		.MAX_READ_BURST_COUNT       (1),
		.MAX_READ_BURST_COUNT_WIDTH (1),
		.DATA_WIDTH                 (32),
		.DATA_BYTEENABLE_WIDTH      (4),
		.DESCRIPTOR_WIDTH           (128),
		.ADDRESS_WIDTH              (32),
		.RESPONSE_FIFO_DEPTH        (256),
		.RESPONSE_FIFO_DEPTH_LOG2   (8)
	) prefetcher_internal (
		.clk                         (clock_clk),                                                    //   input,    width = 1,                              Clock.clk
		.reset                       (~reset_n_reset_n),                                             //   input,    width = 1,                        Clock_reset.reset
		.mm_read_address             (descriptor_read_master_address),                               //  output,   width = 32,             Descriptor_Read_Master.address
		.mm_read_read                (descriptor_read_master_read),                                  //  output,    width = 1,                                   .read
		.mm_read_readdata            (descriptor_read_master_readdata),                              //   input,   width = 32,                                   .readdata
		.mm_read_waitrequest         (descriptor_read_master_waitrequest),                           //   input,    width = 1,                                   .waitrequest
		.mm_read_readdatavalid       (descriptor_read_master_readdatavalid),                         //   input,    width = 1,                                   .readdatavalid
		.mm_write_address            (descriptor_write_master_address),                              //  output,   width = 32,            Descriptor_Write_Master.address
		.mm_write_write              (descriptor_write_master_write),                                //  output,    width = 1,                                   .write
		.mm_write_byteenable         (descriptor_write_master_byteenable),                           //  output,    width = 4,                                   .byteenable
		.mm_write_writedata          (descriptor_write_master_writedata),                            //  output,   width = 32,                                   .writedata
		.mm_write_waitrequest        (descriptor_write_master_waitrequest),                          //   input,    width = 1,                                   .waitrequest
		.mm_write_response           (descriptor_write_master_response),                             //   input,    width = 2,                                   .response
		.mm_write_writeresponsevalid (descriptor_write_master_writeresponsevalid),                   //   input,    width = 1,                                   .writeresponsevalid
		.st_src_descr_data           (prefetcher_internal_descriptor_write_dispatcher_source_data),  //  output,  width = 128, Descriptor_Write_Dispatcher_Source.data
		.st_src_descr_valid          (prefetcher_internal_descriptor_write_dispatcher_source_valid), //  output,    width = 1,                                   .valid
		.st_src_descr_ready          (prefetcher_internal_descriptor_write_dispatcher_source_ready), //   input,    width = 1,                                   .ready
		.st_snk_data                 (dispatcher_internal_response_source_data),                     //   input,  width = 256,                      Response_Sink.data
		.st_snk_valid                (dispatcher_internal_response_source_valid),                    //   input,    width = 1,                                   .valid
		.st_snk_ready                (dispatcher_internal_response_source_ready),                    //  output,    width = 1,                                   .ready
		.mm_csr_address              (prefetcher_csr_address),                                       //   input,    width = 3,                                Csr.address
		.mm_csr_read                 (prefetcher_csr_read),                                          //   input,    width = 1,                                   .read
		.mm_csr_write                (prefetcher_csr_write),                                         //   input,    width = 1,                                   .write
		.mm_csr_writedata            (prefetcher_csr_writedata),                                     //   input,   width = 32,                                   .writedata
		.mm_csr_readdata             (prefetcher_csr_readdata),                                      //  output,   width = 32,                                   .readdata
		.csr_irq                     (csr_irq_irq),                                                  //  output,    width = 1,                            Csr_Irq.irq
		.mm_read_burstcount          ()                                                              // (terminated),                                                  
	);

	read_master #(
		.DEVICE_FAMILY             ("Agilex 5"),
		.DATA_WIDTH                (32),
		.LENGTH_WIDTH              (19),
		.FIFO_DEPTH                (2048),
		.STRIDE_ENABLE             (0),
		.BURST_ENABLE              (0),
		.PACKET_ENABLE             (1),
		.ERROR_ENABLE              (1),
		.ERROR_WIDTH               (1),
		.CHANNEL_ENABLE            (0),
		.CHANNEL_WIDTH             (8),
		.BYTE_ENABLE_WIDTH         (4),
		.BYTE_ENABLE_WIDTH_LOG2    (2),
		.ADDRESS_WIDTH             (32),
		.FIFO_DEPTH_LOG2           (11),
		.SYMBOL_WIDTH              (8),
		.NUMBER_OF_SYMBOLS         (4),
		.NUMBER_OF_SYMBOLS_LOG2    (2),
		.MAX_BURST_COUNT_WIDTH     (1),
		.UNALIGNED_ACCESSES_ENABLE (1),
		.ONLY_FULL_ACCESS_ENABLE   (0),
		.BURST_WRAPPING_SUPPORT    (0),
		.PROGRAMMABLE_BURST_ENABLE (0),
		.MAX_BURST_COUNT           (1),
		.FIFO_SPEED_OPTIMIZATION   (1),
		.STRIDE_WIDTH              (1)
	) read_mstr_internal (
		.clk                  (clock_clk),                                     //   input,    width = 1,            Clock.clk
		.reset                (~reset_n_reset_n),                              //   input,    width = 1,      Clock_reset.reset
		.master_address       (mm_read_address),                               //  output,   width = 32, Data_Read_Master.address
		.master_read          (mm_read_read),                                  //  output,    width = 1,                 .read
		.master_byteenable    (mm_read_byteenable),                            //  output,    width = 4,                 .byteenable
		.master_readdata      (mm_read_readdata),                              //   input,   width = 32,                 .readdata
		.master_waitrequest   (mm_read_waitrequest),                           //   input,    width = 1,                 .waitrequest
		.master_readdatavalid (mm_read_readdatavalid),                         //   input,    width = 1,                 .readdatavalid
		.src_data             (st_source_data),                                //  output,   width = 32,      Data_Source.data
		.src_valid            (st_source_valid),                               //  output,    width = 1,                 .valid
		.src_ready            (st_source_ready),                               //   input,    width = 1,                 .ready
		.src_sop              (st_source_startofpacket),                       //  output,    width = 1,                 .startofpacket
		.src_eop              (st_source_endofpacket),                         //  output,    width = 1,                 .endofpacket
		.src_empty            (st_source_empty),                               //  output,    width = 2,                 .empty
		.src_error            (st_source_error),                               //  output,    width = 1,                 .error
		.snk_command_data     (dispatcher_internal_read_command_source_data),  //   input,  width = 256,     Command_Sink.data
		.snk_command_valid    (dispatcher_internal_read_command_source_valid), //   input,    width = 1,                 .valid
		.snk_command_ready    (dispatcher_internal_read_command_source_ready), //  output,    width = 1,                 .ready
		.src_response_data    (read_mstr_internal_response_source_data),       //  output,  width = 256,  Response_Source.data
		.src_response_valid   (read_mstr_internal_response_source_valid),      //  output,    width = 1,                 .valid
		.src_response_ready   (read_mstr_internal_response_source_ready),      //   input,    width = 1,                 .ready
		.master_burstcount    (),                                              // (terminated),                                
		.src_channel          ()                                               // (terminated),                                
	);

endmodule
