// qsys_top_altera_avalon_st_adapter_1920_7pp2hqi.v

// This file was auto-generated from altera_avalon_st_adapter_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 25.3 109

`timescale 1 ps / 1 ps
module qsys_top_altera_avalon_st_adapter_1920_7pp2hqi #(
		parameter inBitsPerSymbol = 8,
		parameter inUsePackets    = 1,
		parameter inDataWidth     = 32,
		parameter inChannelWidth  = 0,
		parameter inErrorWidth    = 6,
		parameter inUseEmptyPort  = 1,
		parameter inUseValid      = 1,
		parameter inUseReady      = 1,
		parameter inReadyLatency  = 2,
		parameter outDataWidth    = 32,
		parameter outChannelWidth = 0,
		parameter outErrorWidth   = 6,
		parameter outUseEmptyPort = 1,
		parameter outUseValid     = 1,
		parameter outUseReady     = 1,
		parameter outReadyLatency = 0
	) (
		input  wire        in_clk_0_clk,        // in_clk_0.clk,           Clock Input
		input  wire        in_rst_0_reset,      // in_rst_0.reset,         Reset Input
		input  wire [31:0] in_0_data,           //     in_0.data,          Input Data port of Avalon Streaming Sink Interface
		input  wire        in_0_valid,          //         .valid
		output wire        in_0_ready,          //         .ready,         Ready port of Avalon Streaming Sink Interface; indicates when sink interface is ready to receive data
		input  wire        in_0_startofpacket,  //         .startofpacket, Start of packet port of Avalon Streaming Sink Interface;Indicates start of incoming packet
		input  wire        in_0_endofpacket,    //         .endofpacket,   End of packet port of Avalon Streaming Sink Interface; Indicates end of incoming packet
		input  wire [1:0]  in_0_empty,          //         .empty
		input  wire [5:0]  in_0_error,          //         .error,         Error port of Avalon Streaming Sink Interface; each bit corresponds to a different error condition in incoming data, as set in error descriptor
		output wire [31:0] out_0_data,          //    out_0.data,          Output Data port of Avalon Streaming Source Interface
		output wire        out_0_valid,         //         .valid,         Valid data port of Avalon Streaming Source Interface; high when output data is valid
		input  wire        out_0_ready,         //         .ready,         Ready port of Avalon Streaming Source Interface; indicates to source that data can be sent
		output wire        out_0_startofpacket, //         .startofpacket, Start of packet port of Avalon Streaming Source Interface; Indicates start of outgoing packet
		output wire        out_0_endofpacket,   //         .endofpacket,   End of packet port of Avalon Streaming Source Interface; Indicates end of outgoing packet
		output wire [1:0]  out_0_empty,         //         .empty
		output wire [5:0]  out_0_error          //         .error,         Error port of Avalon Streaming Source Interface; each bit corresponds to a different error condition in output data, as set in error descriptor
	);

	generate
		// If any of the display statements (or deliberately broken
		// instantiations) within this generate block triggers then this module
		// has been instantiated this module with a set of parameters different
		// from those it was generated for.  This will usually result in a
		// non-functioning system.
		if (inBitsPerSymbol != 8)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					inbitspersymbol_check ( .error(1'b1) );
		end
		if (inUsePackets != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					inusepackets_check ( .error(1'b1) );
		end
		if (inDataWidth != 32)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					indatawidth_check ( .error(1'b1) );
		end
		if (inChannelWidth != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					inchannelwidth_check ( .error(1'b1) );
		end
		if (inErrorWidth != 6)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					inerrorwidth_check ( .error(1'b1) );
		end
		if (inUseEmptyPort != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					inuseemptyport_check ( .error(1'b1) );
		end
		if (inUseValid != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					inusevalid_check ( .error(1'b1) );
		end
		if (inUseReady != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					inuseready_check ( .error(1'b1) );
		end
		if (inReadyLatency != 2)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					inreadylatency_check ( .error(1'b1) );
		end
		if (outDataWidth != 32)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					outdatawidth_check ( .error(1'b1) );
		end
		if (outChannelWidth != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					outchannelwidth_check ( .error(1'b1) );
		end
		if (outErrorWidth != 6)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					outerrorwidth_check ( .error(1'b1) );
		end
		if (outUseEmptyPort != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					outuseemptyport_check ( .error(1'b1) );
		end
		if (outUseValid != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					outusevalid_check ( .error(1'b1) );
		end
		if (outUseReady != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					outuseready_check ( .error(1'b1) );
		end
		if (outReadyLatency != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					outreadylatency_check ( .error(1'b1) );
		end
	endgenerate

	qsys_top_timing_adapter_1950_4blnw3y #(
		.SYNC_RESET    (0),
		.FIFO_MEM_TYPE (0)
	) timing_adapter_0 (
		.clk               (in_clk_0_clk),        //   input,   width = 1,   clk.clk
		.reset_n           (~in_rst_0_reset),     //   input,   width = 1, reset.reset_n
		.in_data           (in_0_data),           //   input,  width = 32,    in.data
		.in_valid          (in_0_valid),          //   input,   width = 1,      .valid
		.in_ready          (in_0_ready),          //  output,   width = 1,      .ready
		.in_startofpacket  (in_0_startofpacket),  //   input,   width = 1,      .startofpacket
		.in_endofpacket    (in_0_endofpacket),    //   input,   width = 1,      .endofpacket
		.in_empty          (in_0_empty),          //   input,   width = 2,      .empty
		.in_error          (in_0_error),          //   input,   width = 6,      .error
		.out_data          (out_0_data),          //  output,  width = 32,   out.data
		.out_valid         (out_0_valid),         //  output,   width = 1,      .valid
		.out_ready         (out_0_ready),         //   input,   width = 1,      .ready
		.out_startofpacket (out_0_startofpacket), //  output,   width = 1,      .startofpacket
		.out_endofpacket   (out_0_endofpacket),   //  output,   width = 1,      .endofpacket
		.out_empty         (out_0_empty),         //  output,   width = 2,      .empty
		.out_error         (out_0_error)          //  output,   width = 6,      .error
	);

endmodule
