// qsys_top_msgdma_0.v

// Generated using ACDS version 25.3 109

`timescale 1 ps / 1 ps
module qsys_top_msgdma_0 (
		input  wire        clock_clk,                                  //                   clock.clk,               Clock Input
		input  wire        reset_n_reset_n,                            //                 reset_n.reset_n,           Reset Input
		input  wire [31:0] csr_writedata,                              //                     csr.writedata
		input  wire        csr_write,                                  //                        .write
		input  wire [3:0]  csr_byteenable,                             //                        .byteenable
		output wire [31:0] csr_readdata,                               //                        .readdata
		input  wire        csr_read,                                   //                        .read
		input  wire [2:0]  csr_address,                                //                        .address
		output wire [31:0] descriptor_read_master_address,             //  descriptor_read_master.address
		output wire        descriptor_read_master_read,                //                        .read
		input  wire [31:0] descriptor_read_master_readdata,            //                        .readdata
		input  wire        descriptor_read_master_waitrequest,         //                        .waitrequest
		input  wire        descriptor_read_master_readdatavalid,       //                        .readdatavalid
		output wire [31:0] descriptor_write_master_address,            // descriptor_write_master.address
		output wire        descriptor_write_master_write,              //                        .write
		output wire [3:0]  descriptor_write_master_byteenable,         //                        .byteenable
		output wire [31:0] descriptor_write_master_writedata,          //                        .writedata
		input  wire        descriptor_write_master_waitrequest,        //                        .waitrequest
		input  wire [1:0]  descriptor_write_master_response,           //                        .response
		input  wire        descriptor_write_master_writeresponsevalid, //                        .writeresponsevalid
		input  wire [2:0]  prefetcher_csr_address,                     //          prefetcher_csr.address
		input  wire        prefetcher_csr_read,                        //                        .read
		input  wire        prefetcher_csr_write,                       //                        .write
		input  wire [31:0] prefetcher_csr_writedata,                   //                        .writedata
		output wire [31:0] prefetcher_csr_readdata,                    //                        .readdata
		output wire        csr_irq_irq,                                //                 csr_irq.irq
		output wire [31:0] mm_read_address,                            //                 mm_read.address
		output wire        mm_read_read,                               //                        .read
		output wire [3:0]  mm_read_byteenable,                         //                        .byteenable
		input  wire [31:0] mm_read_readdata,                           //                        .readdata
		input  wire        mm_read_waitrequest,                        //                        .waitrequest
		input  wire        mm_read_readdatavalid,                      //                        .readdatavalid
		output wire [31:0] st_source_data,                             //               st_source.data
		output wire        st_source_valid,                            //                        .valid
		input  wire        st_source_ready,                            //                        .ready
		output wire        st_source_startofpacket,                    //                        .startofpacket
		output wire        st_source_endofpacket,                      //                        .endofpacket
		output wire [1:0]  st_source_empty,                            //                        .empty
		output wire        st_source_error                             //                        .error
	);

	qsys_top_msgdma_0_altera_msgdma_1932_k7ydxky sys_tse_msgdma_tx (
		.clock_clk                                  (clock_clk),                                  //   input,   width = 1,                   clock.clk
		.reset_n_reset_n                            (reset_n_reset_n),                            //   input,   width = 1,                 reset_n.reset_n
		.csr_writedata                              (csr_writedata),                              //   input,  width = 32,                     csr.writedata
		.csr_write                                  (csr_write),                                  //   input,   width = 1,                        .write
		.csr_byteenable                             (csr_byteenable),                             //   input,   width = 4,                        .byteenable
		.csr_readdata                               (csr_readdata),                               //  output,  width = 32,                        .readdata
		.csr_read                                   (csr_read),                                   //   input,   width = 1,                        .read
		.csr_address                                (csr_address),                                //   input,   width = 3,                        .address
		.descriptor_read_master_address             (descriptor_read_master_address),             //  output,  width = 32,  descriptor_read_master.address
		.descriptor_read_master_read                (descriptor_read_master_read),                //  output,   width = 1,                        .read
		.descriptor_read_master_readdata            (descriptor_read_master_readdata),            //   input,  width = 32,                        .readdata
		.descriptor_read_master_waitrequest         (descriptor_read_master_waitrequest),         //   input,   width = 1,                        .waitrequest
		.descriptor_read_master_readdatavalid       (descriptor_read_master_readdatavalid),       //   input,   width = 1,                        .readdatavalid
		.descriptor_write_master_address            (descriptor_write_master_address),            //  output,  width = 32, descriptor_write_master.address
		.descriptor_write_master_write              (descriptor_write_master_write),              //  output,   width = 1,                        .write
		.descriptor_write_master_byteenable         (descriptor_write_master_byteenable),         //  output,   width = 4,                        .byteenable
		.descriptor_write_master_writedata          (descriptor_write_master_writedata),          //  output,  width = 32,                        .writedata
		.descriptor_write_master_waitrequest        (descriptor_write_master_waitrequest),        //   input,   width = 1,                        .waitrequest
		.descriptor_write_master_response           (descriptor_write_master_response),           //   input,   width = 2,                        .response
		.descriptor_write_master_writeresponsevalid (descriptor_write_master_writeresponsevalid), //   input,   width = 1,                        .writeresponsevalid
		.prefetcher_csr_address                     (prefetcher_csr_address),                     //   input,   width = 3,          prefetcher_csr.address
		.prefetcher_csr_read                        (prefetcher_csr_read),                        //   input,   width = 1,                        .read
		.prefetcher_csr_write                       (prefetcher_csr_write),                       //   input,   width = 1,                        .write
		.prefetcher_csr_writedata                   (prefetcher_csr_writedata),                   //   input,  width = 32,                        .writedata
		.prefetcher_csr_readdata                    (prefetcher_csr_readdata),                    //  output,  width = 32,                        .readdata
		.csr_irq_irq                                (csr_irq_irq),                                //  output,   width = 1,                 csr_irq.irq
		.mm_read_address                            (mm_read_address),                            //  output,  width = 32,                 mm_read.address
		.mm_read_read                               (mm_read_read),                               //  output,   width = 1,                        .read
		.mm_read_byteenable                         (mm_read_byteenable),                         //  output,   width = 4,                        .byteenable
		.mm_read_readdata                           (mm_read_readdata),                           //   input,  width = 32,                        .readdata
		.mm_read_waitrequest                        (mm_read_waitrequest),                        //   input,   width = 1,                        .waitrequest
		.mm_read_readdatavalid                      (mm_read_readdatavalid),                      //   input,   width = 1,                        .readdatavalid
		.st_source_data                             (st_source_data),                             //  output,  width = 32,               st_source.data
		.st_source_valid                            (st_source_valid),                            //  output,   width = 1,                        .valid
		.st_source_ready                            (st_source_ready),                            //   input,   width = 1,                        .ready
		.st_source_startofpacket                    (st_source_startofpacket),                    //  output,   width = 1,                        .startofpacket
		.st_source_endofpacket                      (st_source_endofpacket),                      //  output,   width = 1,                        .endofpacket
		.st_source_empty                            (st_source_empty),                            //  output,   width = 2,                        .empty
		.st_source_error                            (st_source_error)                             //  output,   width = 1,                        .error
	);

endmodule
