// qsys_top_sysid_qsys_0.v

// Generated using ACDS version 25.3 109

`timescale 1 ps / 1 ps
module qsys_top_sysid_qsys_0 #(
		parameter MANUAL_ID = -87110914
	) (
		input  wire        clock,    //           clk.clk
		input  wire        reset_n,  //         reset.reset_n
		output wire [31:0] readdata, // control_slave.readdata
		input  wire        address   //              .address
	);

	altera_avalon_sysid_qsys #(
		.TIMESTAMP     (0),
		.USE_MANUAL_ID (1),
		.MANUAL_ID     (MANUAL_ID),
		.HASH_ID       (39)
	) sys_sysid (
		.clock    (clock),    //   input,   width = 1,           clk.clk
		.reset_n  (reset_n),  //   input,   width = 1,         reset.reset_n
		.readdata (readdata), //  output,  width = 32, control_slave.readdata
		.address  (address)   //   input,   width = 1,              .address
	);

endmodule
